== Priority Area 1: Science and Research 

_Improving biodiversity evidence for scientific research and understanding_

=== 1.	Engage research communities for data mobilization and use

Nodes play an essential role in building engagement with researchers within their countries and networks, promoting open science principles (in line with the https://en.unesco.org/science-sustainable-future/open-science/recommendation[UNESCO open science recommendation^]) and building communities of data publishers and users. Research communities can help to identify data gaps, data needs, and challenges in the use of the available data that can help nodes to prioritize activities. Several nodes have succeeded in embedding GBIF within academic training programmes (see https://www.gbif.org/article/aA0MjVddRiRFOX2SEs7mT/[guiding example from Benin^]), developing capacity and encouraging new generations of researchers to follow open science practices. GBIF’s focus on thematic communities, continuing with thematic communities around DNA-derived and disease vector data, and transitioning from 2023 focus on soil and freshwater data to invasive alien species and agrobiodiversity in 2024, will lead to growing interest in data publishing and data use from researchers that will seek to connect with nodes for support.
Nodes are encouraged to:

* Engage with scientific leaders in biodiversity sciences to build and develop a scientific community around the node. The https://www.gbif.org/data-use[country filter of literature tracking and annual _Science Review_^] can help identify active users of GBIF-mediated data in the country. 
* Encourage local researchers to join the https://www.gbif.org/ambassadors[biodiversity open data ambassadors programme^]. Cultivate active relationships between the node and ambassadors to promote GBIF data use in research through national and regional conferences and other relevant fora.
* Organize national or thematic events targeting research communities, including focus on training for DNA derived data and GBIF (see available https://doi.org/10.35035/doc-vf1a-nr22[guide^] and https://www.gbif.org/training[training materials^]).
* Promote and participate in data mobilization actions relating to thematic approaches, such as calls for data papers. For 2024, nodes should consider contributing to the Work Programme focus on invasive alien species and agrobiodiversity, consulting with the Secretariat on potential ways to get involved.
* Promote the https://www.gbif.org/data-use-club[Data Use Club^] within research and student communities as a means to develop data literacy skills, for example, by organizing a national/thematic team (see https://vimeo.com/711112378?embedded=true&source=vimeo_logo&owner=8757851[guiding example from Colombia^]).
* Engage with national graduate schools, universities and other key partners in higher education aiming at making data skills and GBIF training an essential part of university curricula (using the increasing popularity of teaching R and the https://www.gbif.org/article/aA0MjVddRiRFOX2SEs7mT[Master's programme in biodiversity informatics in Benin^] as examples).
* Increase promotion of the https://www.gbif.org/article/44SftFORi0A6mwGK4sgAKW/[Graduate Researchers Award^] and https://www.gbif.org/ebbe[Ebbe Nielsen Challenge^] to encourage and recognize innovative research use of GBIF-mediated data.
* Support the development and implementation of national policies on open science and data to implement FAIR and CARE principles.
* Know, seek and develop key partnerships with national, regional, global and thematic research infrastructures to help drive the agenda around data-intensive biodiversity research.

== Priority Area 2: Policy and Partnerships

_Developing partnerships that benefit policy and society_

=== 2.	Support national biodiversity commitments and the science-policy interface

Through partnerships and coordination, nodes can enable data flows into indicators and reporting processes relating to biodiversity status and trends, supporting commitments under the Convention on Biological Diversity (CBD) and the Sustainable Development Goals. By building linkages with the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES), nodes can support biodiversity assessments by providing access to biodiversity data and enabling policy-related research based on GBIF-mediated data. These linkages can also support the nodes in terms of raising awareness of the value of open biodiversity data to national policy and commitments, as well as identifying policy-relevant gaps in data availability.

Nodes are encouraged to:

* Make connections with the CBD focal points or even include them in their node team to support the implementation of national commitments under the Convention on Biological Diversity (CBD).
*	Pay particular attention during 2024 to the process of revising National Biodiversity Strategies and Action Plans (NBSAPs), and developing national targets and indicators for reporting progress towards goals and targets of the Kunming-Montreal Global Biodiversity Framework (CBD), seeking advice from the Secretariat if required.
* Engage with the IPBES national focal points (see https://www.gbif.org/article/6Or2284ny8cU2SaAIok8Ug/[guiding example from Belgium^]) and with other biodiversity-related conventions to discuss data flows and known data gaps.
* Relate data use cases and other GBIF activities to supporting the Sustainable Development Goals (SDGs) (see https://www.gbif.org/article/TbnYdzigUnP08rQbcwh56/[guiding example from the Chinese Academy of Sciences^]).

=== 3. Promote open biodiversity data approaches within the business and finance sectors

In recent years, several nodes have scaled up engagement with the private sector resulting in increased data mobilization, partnerships, and communication materials to support further engagement (see the resources developed and available for reuse through the https://www.gbif.org/project/2Zik1tfJoh3C92ZslvhDIr/[CESP OpenPSD project^] and the https://www.gbif.org/business[GBIF business sector page^]). 

Nodes are encouraged to:

* Engage with the private sector through sectoral associations, individual companies and consultancies to promote publishing of data associated with environmental and social impact assessments (ESIA) as well as ongoing biodiversity monitoring.
* Where appropriate and practical, support data publication from the private sector through guidance and use of data publishing platforms.
* Engage with national environment monitoring authorities to encourage mandatory publishing of primary biodiversity data through GBIF as part of the ESIA process (see resources developed by the https://www.gbif.org/project/83336/[CESP BIREME project^]).
* Engage with national development agencies to promote requirements for data publication in projects supported by development finance or overseas development assistance, including through the https://www.gbif.org/data4nature[Data4Nature initiative^] in consultation with the Secretariat.

== Priority Area 3: Community and Capacity

_Developing the GBIF network to meet future needs and challenges_

=== 4. Support node development through knowledge sharing and mobility of skills

All nodes have limited resources. Ensuring capacity at the node level in terms of a skilled and stable node team remains a priority. Nodes should strive for a team of at least four full-time equivalents (FTEs) per country node. A node team would typically include a Node Manager, an IT-developer, a data manager and a node staff member for scientific outreach and communication. Recognizing that this is a combined responsibility with the Heads of delegation, Node managers will report on progress to establish such functional node teams.

Nodes benefit greatly from the sharing of knowledge and experience with other nodes in the network. The GBIF Capacity Enhancement Support Programme (CESP) is a key mechanism for supporting collaborative projects between nodes.

In 2024, GBIF will explore opportunities to enable secondments and work exchange within the GBIF network. Nodes are encouraged to contribute ideas on how such mechanisms can support capacity development for strong nodes.

Nodes are encouraged to

* Assist in communicating the value of GBIF, including making use of the https://www.gbif.org/news/5WZThcL928vmPnSvrGhZfE/[economic valuation of the GBIF network^], to potential partners at all levels.
* Collaborate with other nodes and partners to support active participation in GBIF by more countries.
* Assist with the onboarding of new nodes in the network.
* Contribute to the discussions on secondments and work exchange within the network.
* Continue to collaborate with other nodes on capacity development, including through the https://www.gbif.org/programme/82219/[Capacity Enhancement Support Programme^].
* Contribute to consultations on the future of the CESP programme to ensure it can support capacity needs across all GBIF Participants.
* Continue training and engagement actions to strengthen and expand national data publication and use.
* Develop and enhance https://www.gbif.org/hosted-portals[hosted portals^] and https://living-atlases.gbif.org/[Living Atlases^] for national, regional and thematic data communities.

=== 5. Develop capacity within regional communities of practice

Since 2021, GBIF has contracted regional support teams in Africa, Latin America and the Caribbean, Asia, and most recently in Europe and Central Asia. The work of these teams focuses on geographic areas that are not yet supported by GBIF nodes and covers engaging data holding institutions, supporting data publishing, developing skills and engagement within the community of practice and providing feedback to GBIF on regional capacity needs.  They can also provide ad-hoc support and specific training to existing GBIF nodes upon request.  This approach complements the ongoing efforts of node managers, regional representatives, and volunteer trainers and mentors, to develop regional communities of practice engaged in data mobilization and use through GBIF. Nodes have an essential role in guiding the work of regional support teams and future regional-level support for capacity and participation.

Interregional partnerships under the umbrella of GBIF are encouraged to support more extensive capacity building and / or sound academic training of students in order to promote a new generation of data scientists capable of data use to inform decisions on biodiversity conservation and sustainable use across regions.


Nodes are encouraged to:

* Further explore partnerships between nodes and the regional support teams to support the work of the nodes, as well as broader capacity development in the region, and contribute to discussions on the future of this approach.
* Contribute to the development of future capacity development programmes, such as the https://www.gbif.org/bid[Biodiversity Information for Development^] (BID) programme.
* Participate in regional nodes meetings and discussions on strengthening regional engagement in GBIF.

== Priority Area 4: Infrastructure and data products

_Maintain and evolve infrastructure to advance biodiversity-related knowledge_

=== 6. Strengthen support services for collection communities 

Nodes have been actively contributing to updating and enriching the content of the https://www.gbif.org/grscicoll[Global Registry of Scientific Collections^] (GRSciColl), supported by videos and training activities. For institutions with collections that are not yet publishing data, updating their records in GRSciColl can be a simple first step towards engaging them as data publishers in the future. This work helps to raise the visibility of collections, including those that have not yet been digitized.

Nodes are encouraged to:

*	Contribute actively to updating GRSciColl and engaging institutions with collections and relevant societies and networks in data mobilization.
* Support the development of https://www.gbif.org/hosted-portals[hosted portals^] for collections.
* Participate actively in the implementation of the https://scientific-collections.gbif.org/road-map[GRSciColl road map^] by providing feedback on new features and reviewing the data schema.

=== 7. Contribute to data model enhancements

Community engagement is essential in the work on diversifying the data model. Case studies are being prepared in collaboration with community members who have identified the need to better support the publishing of their specific type of biodiversity data. These case studies are open for ongoing comments and inputs. Nodes and community members are contributing to the series of webinars exploring progress towards the new data model. The Integrated Publishing Toolkit (IPT) is being enhanced to support data publishing using the new model. This work will continue in 2023 and will rely on community feedback, testing, and engagement through the nodes. Nodes, in their role of supporting data mobilization activities from their communities, will need training materials and documentation to allow them to efficiently promote data publishing via the new model. Ultimately, this should enable GBIF and nodes to provide the data infrastructure for a broader set of biodiversity data holders and users.

Nodes are encouraged to:

* Participate in the regular webinars exploring the https://www.gbif.org/new-data-model[new data model^].
* Engage in the development and testing of new training materials and documentation to support data publishing with the new data model.
