[appendix]
== Participant plans 2024

Towards the end of each year, the GBIF Secretariat asks Participants to outline any work they have aligned to the priority areas identified in the GBIF’s work programme for the upcoming year. This appendix includes the plans Participants provided for 2024.

[[plans-priority-1]]
=== Priority Area 1

==== Andorra

New scientific monitoring programmes have been set up, and we need to continue and also launch new participatory science programmes (collaboration with the Government of Andorra should facilitate this). There has also been a delay in integrating the data into the GBIF (see below).

[[acb-1]]
==== ASEAN Centre for Biodiversity

To continue and expand the technical capacity building and data mobilization in Southeast Asia.

==== Australia

===== Activity 1.1

- ALA continues to experiment with uploading DNA-derived data. There is now a postdoctoral fellow engaged in CSIRO who is looking at the challenges in this area. She was actively engaged in discussions about eDNA data during the TDWG conference in Hobart in 2023 and also participated in the GBIF-run workshop adjacent to the GB30 meeting. 
- The Australian Research Genome Atlas (ARGA) has received funding for another year.

===== Activity 1.2 

The status of the EcoCommons project in Australia has changed and it will move to be run under the auspices of a different university in 2024. How actively ALA will participate in the new iteration of this project is as yet unknown.

==== Belgium

- Advance collaborative activities with soil, freshwater, disease vector and eDNA research communities
* Support biodiversity data mobilization
* Improve visibility of Federal collections
* Atlas of Living Flanders
* Organisation of EBR 3 conference (with NLBIF and LuxBIF), see https://www.biodiversity.be/EBRIII
* Keep an eye on EOSC development
* Networking on IAS

==== Benin

Continue data use to inform decision on biodiversity conservation

==== Biodiversity Heritage Library

Future data deposits are anticipated in 2024, but are wholly dependant on staff capacity to do the data transformation work required.

==== Brazil

Test the GBIF eDNA tool and publish eDNA data. Study in more detail the advantages and disadvantages of implementing DOIs at national level together with other research institutions. Create and follow discussion of research/working groups on FAIR and CARE principles at a national and international level. Automate publishing and updating of occurrence and ecological data in SiBBr and implement test with the new GBIF data model and Humboldt extension. In addition, work together with the group on vectors of human desases by organizing a symposium on vector data and seek for more funding to continue the development of the PREVIR application that allows the collection of virus data in different animals and automatic standardization for publication in the IPT.

==== Cameroon

- Participation in workshops organized by research institutes. These activities are not planned and can take place at any time during the year. Example: Presentation of the GBIF platform and its use as a decision-making tool by policy-makers in Cameroon will be made during a workshop organized by the Institut de Recherche Agricole pour le Développement (IRAD) scheduled for February 07, 2024.
- Support for researchers in the use of GBIF data in the production of scientific articles.

==== Chile

- Promote the mobilization and use of biodiversity data to support research and public policy management. 
- We continue to establish agreements with new partners, transfer or provide assistance to publishers and propose working groups to advance a public policy on biodiversity data.
- By 2024, the node is expected to be consolidated through network-wide governance, which will enable the generation of a roadmap for the next five years.

==== Chinese Academy of Sciences

Country Research Report of GBIF data usage in Asia based on literature data, from different scientific disciplines and thematic areas.

==== Chinese Taipei

- Engage with disease vector, eDNA, alien species and agrobiodiversity research communities and facilitate data publication.
- Identify data gaps in Taiwan and propose a strategy for filling the gaps.
- Provide financial support for data paper publishing.
- Provide helpdesk services for data mobilization.
- Organize workshops and promotion events at scientific conferences.
- Promote applications of biodiversity open data in research on social media.
- Establish data pipelines and help data management for Taiwan's long-term socio-ecological research project.

==== Colombia

- Continue the participation in the national task group on migartory, threatened, and invasive alien species, and publish the national reference checklist on migratory,  invasive, exotic and invasive potential species.
- Strengthen and expand support and guidance on mobilizing DNA-derived, for which we will continue making test in the new tool involving intersted publishers.
- Support and review the new data models developed though GBIF efforts and make internal test to contribute to the reviewing process and capture needs and suggestions from research communities regarding the development of the GBIF data model.
- Promote the Data Use Club within research and student communities as well as the calls for the Ebbe Nielsen Challenge and Graduate Researchers Award.

==== Costa Rica

Establish alliances with representative NGOs that have projects in different areas of the country and in relevant topics (such as alien species, Human-wildlife conflict, biodiversity in human impacted areas, etc) whose biodiversity data is key to filling knowledge gaps in the country. Contact with researchers and projects related to DNA-derived data in the country in order to incorporate this information to GBIF.

[[croatia-1]]
==== Republic of Croatia

Croatia in cooperation with the GBIF Belgium and the Habitat Foundation (within the CroMent project), will conduct workshops that will encourage the mobilization and use of data on biodiversity. Representatives of the scientific community will attend the workshops, which will certainly increase the mobilization of data in the territory of the Republic of Croatia. National biodiversity database, based on Atlas of Living Australia, is expected to be publicly available by September 2024

==== Denmark

The development of the Arter.dk national species portal is continuing in 2024. DanBIF and Arter.dk is working towards supporting collecting and sharing aquatic occurance data including governmental nature monitoring data. Furthermore, we are working towards being able to support sound-based occurrence observations including automated species recognition. DanBIF also keeps the taxonbase in Arter.dk updated  in collaboration with a newly established Danish taxon advisory board. DanBIF plans to implement the new data model specifically to mobilise a large camera trap dataset of small mammals. DanBIF have engaged with new categorise of data providers such as NGO's and nature consultancy companies.

[[eabcn-1]]
==== East Asia Biodiversity Conservation Network

Continue to encourage and support the discovery of undigitized taxonomic information and its inclusion in the GBIF

==== Estonia

We will focus on eDNA data mobilisation and publishing. Updated version of the UNITE SH DOIs will be released and made available for the GBIF taxonomic backbone. New digital tools for the eDNA research will be developed and  implemented in the PlutoF platform which will make sharing and publishing eDNA data easier.

==== Finland

FinBIF and its partners plans to investigate how to mobilise eDNA based biodiversity including soil derived DNA data. A focus for 2024 will be on addressing knowledge gaps within FinBIF's current biodiversity datasets. We plan to address how we make sensitive biodiversity data available to our data users, building on our past work in this area.

==== France

-	Engagement with national research communities relating to data mobilization and use, targeting thematic priorities and French overseas.
-	Contribution on national working groups: WP Traits and WP Sequence.
-	Encourage participation in testing the new data model.
-	Plan to organize a GBIF France day to reinforce visibility and data use in France.
-	Keep track of use through GBIF monitoring.
-	Communicate on outputs of GBIF’s contribution to latest biodiversity modelling approaches (B-Cubed, BioDT…).
-	Consider discussions on data from natural habitat ecosystems.
-	The French node manager is an official member of REISO : French network of international experts organized by the ministry of research to promote open science and French policy regarding open science.

==== Georgia

- Continue research on the ways of entry of invasive alien species in 2024.
- Continue development of the National species restoration plan  for adoption.

==== Germany

The GBIF node delegates, manager and staff will continue to attend relevant scientific conferences to promote GBIF through appropriate communication materials and presentations. They will also participate in GBIF meetings and conferences, e.g. the planned ECA meeting in Zagreb. In 2024, the organisations of the GBIF Germany node network intend to mobilise occurrence and checklist data via data pipelines of the NFDI4Biodiversity consortium. Thus, GBIF is becoming part of the German National Research Data Infrastructure (NFDI).

==== Ireland

As part of the National Biodiversity Action Plan for Ireland (which will be launched in 2024) the National Biodiversity Data Centre is to:
- update to the State of Knowledge and Key Knowledge Gaps in Ireland’s Biodiversity report as the basis for development of a national biodiversity monitoring framework by 2024.
- produce and implement a Biodiversity Citizen Science Strategy to promote citizen engagement with both terrestrial and marine biodiversity and to develop greater awareness of the value of local biodiversity by 2024.
- Ongoing activities to support science and research for different project areas including  All Ireland Pollinator Plan; European Innovation Partnerships projects; Invasive Species, Farmland projects which will produce high quality data.
- Attend relevant scientific conferences to promote GBIF through appropriate communication materials and presentations.

==== Madagascar

- Revitalising the MadBIF network.
- Diversification of data types is among MadBIF's priorities. Data on microorganisms (fungi, bacteria).
- amélirer la base de données sur la biodiversité en Mauritanie et dynamisation des points focaux du GBIF-Mauritanie.

==== Mauritania

- Continue investigation activities into the biodiversity of continental wetlands in Mauritania
- Improve the botanical collection

==== Mexico

- Support implementation of national policies on open science, developing capacity to follow open science practices
- We published the calls, but on this occasion no candidates presented themselves. It has been published on the CONABIO website and we hope to spread it further. In all national and regional forums in which the National Biodiversity Information System (SNIB) is presented, we promote the use of DOIs.

==== Netherlands

===== Activity 1.1

- Priority area Soil: NLBIF puts special attention to soil biodiversity and aims to mobilise more datasets with RIVM
- Priority area DNA barcoding and metagenomics: NLBIF is partner in the MetaPlantCode project that was funded by Biodiversa+ which will mobilise a substantial amount of eDNA data to GBIF over the next three years.
- Priority area Business sector: NLBIF is involved through its host institute - Naturalis Biodiversity Center - in collaborations with KPMG and BNP Paribas where the impacts and dependencies of business activities on biodiversity are assessed. Parts of these analyses depend on biodiversity data mobilzed through GBIF. Through this engagement businesses are also motivated to share their biodiversity data from environmental impact assessments.

===== Activity 1.2
Through the collaboration with KPMG NLBIF aims to inform the private sector on distinguishing the negative impacts on biodiversity of  climate change from the impacts of business activities through predictive modeling.

===== Activity 1.3
The Dutch, Belgium and Luxembourg GBIF nodes organize the https://www.biodiversity.be/EBRIII/[Empowering Biodiversity Research III conference^] on March 25 and 26 at Naturalis Biodiversity Center that promotes sharing and using of GBIF data for research and policy.

==== New Zealand

- We plan to hold a GBIF-NZ workshop with key stakeholders and government agencies to communicate and engage with data holders. This will provide an opportunity to promote the value of GBIF to NZ,  as well as to test and refine the draft strategy, roadmap and workplan for New Zealand. At this we will continue work to identify priority datasets for mobilisation to improve data coverage across the thematic areas of relevance (e.g. invasive species and eDNA). 
- Development of a simple process to increase awareness and applications from NZ to the graduate awards.
- Support newly registered NZ data publishers to mobilise their data sets using the hosted-ipt instance.

==== Nordic Genetic Resource Center

We are working on DOIS to our MCPD data. 

==== Poland

- to continue publishing digitized data through GBIF.
- to include GBIF as a key component of data publishing for all planned large digitization projects in the country.
- to promote GBIF at biodiversity-related scientific conferences.
- to include GBIF usage and data publishing in academic education.

==== South Africa

- Data use and impact of South African data to be taken forward in 2024.  Further efforts to support the mobilization of DNA derived data will be taken forward.  
- GRA will be promoted in 2024 and is supported by a national committee.
- Promote efforts around use and citations of GBIF mediated data, at relevant conferences and stakeholder events as opportunity arises.
- Further efforts to take forward mass digitization efforts using the Conveyor Belt System.
- Take steps to advance work around data paper publication.

==== Spain

- We maintain our core activities (operations) focused on increasing biodiversity data coming from Spanish institutions and projects, and promoting GBIF-mediated data usage. This year we plan to prioritize data coming from the private sector and data related to areas relevant in conservation and ecosystem services as soil and freshwater biodiversity.  
- The 2024 training plan includes two workshops focused on modelling and data cleaning for data modelling. 
- We plan to develop during 2024 some specialized views of GBIF data in https://datos.gbif.es[our data portal^] addressing specific communities (ecologists, managers, schools).

==== Sweden

===== Activity 1.1: 

Mobilization and use of biodiversity data: GBIF Sweden will continue to focus on mobilizing DNA-derived data and monitoring data. As an integral part of https://biodiversitydata.se/[SBDI^], GBIF Sweden will contribute to the establishment of metagenome sequence catalogs for key Swedish biomes not covered by international efforts. We plan to recruit a data steward (50% FTE) who will conduct more active outreach focused on data mobilization and networking. As part of the introduction the new data steward will make an updated data gap analysis and inventory of possible Swedish data stakeholders. GBIF Sweden will continue to partner with the Swedish National Data Service (SND) to set up a national (research) metadata portal (https://demo.researchdata.se/en[view demo^]). This portal will deliver national data to EOSC.

===== Activity 1.2: 

Biodiversity modelling: Participate in and co-organize the SBDI Days with focus on Data-driven ecology.

===== Activity 1.3: 

Open science principles: Continue to monitor and participate (as reviewer) in the process of producing https://www.kb.se/samverkan-och-utveckling/nationella-riktlinjer-for-oppen-vetenskap/utkast-till-riktlinjer.html[national guidelines for open research and open data^]. We further plan to organize a FAIR data workshop.  

[[tajikistan-1]]
==== Republic of Tajikistan 

In 2024 I'm going to submit new project to CESP. 

==== Togo

===== Activity 1.1. 

GBIF Togo plans to continue mobilizing data on the diseases sector, and using data by modelling in the same area.

===== Activity 1.2

Capture needs and suggestions from Togo public research communities (universities, institutes, NGOs) regarding the development of the GBIF activities (data mobilizing and data use)

==== United Kingdom

Building  on the experience of the live IPNI registration system: https://www.ipni.org/registration/. Kew and Natural History Museum staff will argue and support proposals for registration of plant names at the nomenclatural session of the  International Botanical Congress July 2024 in Madrid.

==== United States

Continue work from 2023, including: 

- Lead an Earth Science Information Partners (ESIP) Cluster to promote the use of standards, e.g. Darwin Core, for biological observation data. 
- Promote the use of the DNA Derived Data extension in US eDNA forums. 
- Contribute to a data dialog session at Ecological Society of America annual meeting in collaboration with key biodiversity data entities. 	
- Develop some more general material to deploy at outreach events, and test e.g, at Entomological Society of America and others 
- Participate in working groups to develop DNA-derived data standards and practices toward a streamlined publication workflow 
- Highlight and illustrate uses of GBIF-mediated data across scientific disciplines and thematic areas through GBIF.US

==== Uruguay

Publishing DNA-derived data. 

==== Uzbekistan

In 2024, Uzbekistan will host a GBIF workshop for the first time with the participation of scientists from Central Asia and other surrounding countries. More than 300,000 georeferenced points will be uploaded to GBIF.

[[wfcc-1]]
==== World Federation for Culture Collections

Improving biodiversity evidence for scientific research and understanding is long overdue and it is the right action to be taken.

==== Zimbabwe

Mobilise data on bacteria and fungul communities in forest and cropland soils in addition to plants and arthropods.

[[plans-priority-2]]
=== Priority Area 2

==== Andorra

* Continue and advance collaborative activities with public administrations to publish their data on the GBIF portal.
* Collaboration with public administrations, and in particular the Andorran government, has been strengthened and a common database is being created to feed them in order to publish their data on the GBIF portal.

[[acb-2]] 
==== ASEAN Centre for Biodiversity

Organized a Bioland Tool workshop for 3 ASEAN Countries with the support from CHM CBD secretariat.

==== Australia

ALA's most relevant work, in addition to advocacy to Australian government regarding international policy commitments, will be to develop standardised data capture tools for data capture in the field. ALA's collaborations with Indigenous Ranger groups is likely to be the catalyst for the development of new tools.

==== Belgium

Achieved in 2023:

* Riparias project ongoing
* IPBES communication products targeted at BE stakeholders 
* Biodiversa  activities

Not achieved or postponed:

* Engaging BE experts in IPBES workplan
* IUCN Belgium Day
* Biodivclim
* Biodivscen

Ongoing activities:

* Finish RipaRIAS project
* Handover Biodiversa+ project to Belspo team
* Establish collaboration with Sciensano on One Health
* Engage BE experts in IPBES, IUCN workplan

==== Benin

Partnership was reinforced through training in the framework of workshop. Researchers, policy and decision makers were invited and attended the workshops.

==== Brazil

New partnerships with Brazilian institutions, technical assistance in data mobilization by government agencies and promoting the use of creative commons licenses as well as dissemination of GBIF Brazil. Recently, in 2023 the Brazilian Institute of Economy and Statistics (IBGE) published the first report on “Quality assessment on Brazilian Biodiversity data” using data available on SiBBr’s (GBIF Brazil). 
More information: https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38420-ibge-avalia-os-registros-de-dados-sobre-a-biodiversidade-brasileira[BGE assesses data records on Brazilian biodiversity^]  ; https://biblioteca.ibge.gov.br/visualizacao/livros/liv102046.pdf[Avaliação dos dados sobre a biodiversidade brasileira^]

==== Cameroon

Participation à l’atelier de lancement du projet Global Biodiversity Framework Early Action Support (Africa 4)

==== Chile

Incorporate GBIF in the process of implementing the Support implementation of the post-2020 Global Biodiversity Framework in Chile.

==== Chinese Academy of Sciences

1. Node staff attended several CBD & IPBES meetings and communicated with participants about the work of GBIF. 
2. Organized an online webinar to encourage data owners to join the GBIF network.

==== Chinese Taipei

- Engaged with government agencies, companies and consultancies related to environmental impact assessments.
- Collected cases of using biodiversity open data in policy making.
- Organized a data mobilization workshop for environmental impact assessments.
- Engaged with biodiversity-related government agencies through Taiwan Biodiversity Information Alliance.

==== Colombia

From the business sector activities we acquired 13 publishers and reach near to 4 million records total, therefore consolidating the alliance with ANDI through the creation of https://www.gbif.org/es/network/2ee1bff7-0b34-4fa3-9433-feaa7c6ee08b[the Colombian Biodiversity and Development GBIF network^].

==== Costa Rica

We are actively working on the implementation of Creative Commons licenses in our national plataform BiodataCR to facilitate correct citation of the databases and the corresponding credit. Also, we are participating in the CESP project called "Enhancing data publication, access and use capacities in theprivate sector" wich seeks to strengthen collection and publication of data by public and private business sector.

[[croatia-2]]
==== Croatia, Republic of

GBIF accepted the CroMent project that will help in realization of the priority area 2.

==== Denmark

DanBIF is actively involved in increasing the awareness of the importance and strength in the use and provision of data to GBIF towards the industry and financial sector. 

[[eabcn-2]]
==== East Asia Biodiversity Conservation Network

Assess the Red List of Threatened Endemic sprcies in East Asia to implement conservation Biodiversity according to the GBF.

==== Estonia

Estonian GBFI node was involved in the creation of the Environmental commission of the Estonian Academy of Sciences.

==== Finland

In collaboration with the Finnish Environment Institute we have implemented a web-based service for the automatic generation of biodiversity indicators. These indicators can be used to help Finland's relevant bodies in reporting for targets under the Global Biodiversity Framework. FinBIF has frequently engaged directly with ministries and other Finnish government bodies throughout 2023 on nature conservation and environmental decision making. A new GIS data product has been released to aid Finland's 15 Centres for Economic Development, Transport and the Environment in decision making around land-use planning and its impact on threatened species. Biodiversity data search capabilities via our web portal have been enhanced to improve the usability for private sector environmental consultants and forest industry partners. In 2023 there were over 2000 data requests made by this data user type using FinBIF's restricted data services. In 2023 private sector data mobilisation has increased with multiple environmental consultancies sharing occurrence records they have collected via our "Data Bank" service.

==== France

- Continue liaising with CHM focal point and the french BON of GEOBON (lead by PNDB national pole of biodiversity data from the research ministry and SIB Information system for biodiversity from ecology ministry).

- Involvement in EU projects such as Biodiversa  (pilot use-case on DWC and monitoring data) and DiSSco (e.g. : contribution in training work package in DiSSCo prepare).

- Engagement with the business and finance sectors to encourage sharing and use of biodiversity data : Data4Nature (AFD), DEPOBIO (legal repository of observational data from impact studies for private sector), international private companies based in France.

==== Georgia

- Node Manager nominated by Georgia is responsible for setting up the National  Biodiversity Monitoring System.
-  Node manager has participated in the update of the Red List of Georgia, this process has been done for each taxonomic group of species.

==== Germany

Technical Expert Group for the National Biodiversity Indicators held regular meetings to update suite of Biodiversity Indicators. 

==== Ireland

- The National Biodiversity Data Centre ensured that Ireland increased the quantity and quality of its contributions to GBIF through continued collaborative activities with public administrations.
- The National Biodiversity Data Centre provides the information, data and reporting services on behalf of the State Agency with implementation of the EU Regulation on Invasive Alien Species."

==== Madagascar

The synergy between the entities working on biodiversity (CHM Madagascar, IPBES...) and MadBIF will be reinforced

==== Mauritania

Développer le partenariat avec des institutions publiques et privées. Prospect avenues for collaboration with GBIF nodes, in particular the Belgian node. 

==== Mexico

- Increase of 1.2 million occurrence records in 11new datasets. Total of  25,009,927 publisher occurrences.
- Update 975 datasets, mainly due to taxonomy update and geographic validation processes.
- National checklist "Lista de las especies de Ranunculaceae con distribución en México" and "Lista de las especies de Brassicaceae con distribución en México" were published.
- New regional checklist "Lista de especies de abejas nativas del Parque Nacional Barranca del Cupatitzio (Área de montaña), Uruapan, Michoacán, México." was published by new publisher "Instituto de Ecología A.C. Centro Regional del Bajío". 
- Four new publishers: "Universidad Michoacana de San Nicolás de Hidalgo Facultad de Biología", "Instituto de Ecología A.C. Centro Regional del Bajío", "Universidad Autónoma de Aguascalientes", and "ECA Liquefaction S. de R.L. de C.V." ECA is a company of private sector."
- Increase number of occurrence records, checklist and national publishers.

==== Netherlands

===== Activity 2.1

- NLBIF aims to increase the relevance of Dutch biodiversity data for CBD indicators through engagement with relevant stakeholders in the Netherlands.
- NLBIF aims to establish connections with the national focal points for the CBD, CMS, CITES and Ramsar.

===== Activity 2.2

NLBIF aims to link Dutch data publishers that hold marine biodiversity data that is currently shared through the https://www.informatiehuismarien.nl/uk/[Informatiehuis Marien^] to GBIF.

===== Activity 2.3

- NLBIF is working on mobilising species list with protected species according Dutch and EU laws to COL CheckListBank to increase the policy relevance of GBIF mediated biodiversity data.
- NLBIF aims to become active in mobilising data from Environmental Impact Assessment that are commisioned by governmental organisations and financial institutions.
- NLBIF collaborates on a Biodiversa  application which currently is pending decision.

===== Activity 2.4

NLBIF is trying to establish connections with Dutch Investment Companies to mobilise biodiversity data under the implementation of the Equator Principles.

==== New Zealand

- Some progress made by GBIF-NZ node to support implementation of national commitments under the Convention on Biological Diversity (CBD) by meeting with two key central government agencies (Ministry for Primary Industries and Department of Conservation) to identify and seek agreement to mobilise primary invasive species datasets (e.g. weeds and mammal pests). 
- GBIF Node participation in workshops to develop Monitoring and Reporting Framework for Te Mana o te Taiao – Aotearoa New Zealand Biodiversity Strategy to promote the utility of GBIF infrastructure for data mobilisation to support/underpin NZ contribution to post-2020 Global Biodiversity Framework.

[[nigeria-2]]
==== Nigeria, Federal Republic of

To develop partnerships that will benefit policy and society

==== Nordic Genetic Resource Center

We are working within the post-2020 Global Biodiversity Framework 

==== Poland

Established communication with the General Directorate for Environmental Protection, responsible for harmonization of biodiversity monitoring data collected by the Ministry of Climate and Environment and its agencies.

==== South Africa

South Africa has participated on IPBES Knowledge and Data Task Force.

==== Spain

As a follow-up of the 2023 LAC Nodes regional, we identified an emerging opportunity in the new Biological Diversity Framework approved in Montreal, which includes for the first time a ""Monitoring Framework"", which necessarily requires greater participation of science and data-based evidence. In coordination with the LifeWatch ERIC we organized and carried out  an expert meeting for positioning GBIF in the new CBD framework, and to develop a training module for the nodes global community.  This was held in Seville, funded by CSIC (through a EU project), and  having among participants GBIF Node representatives from six countries and GBIF Secretariat
https://www.gbif.es/experts-meeting-gbif-in-support-of-the-indicators-for-the-kunming-montreal-global-biodiversity-framework/.
 
Our linkages and collaborations with administrations and policy makers in Spain are strong. A reflection of this is the organization of the 2023 Conference on ""Biodiversity Information and Environmental Administrations"". This a highlight in our https://www.gbif.es/jornada/jornadas-sobre-informacion-de-biodiversidad-y-administraciones-ambientales-2023/[yearly agendas^].

==== Sweden

- Explore possible partnerships and funding opportunities for financing the planned BIECA-project.
- Continue to build the SBDI network in Sweden and promote GBIF within this community.

[[tajikistan-2]]
==== Tajikistan, Republic 

I met with young students which are interesting working with data and database.

==== Togo

===== Activity 2.3
Participating on CABES/IPBES activities (online course on ‘Developping National Science-Policy-Practice Interface Platforms and Networks’ to develop competences and expertise on this area. 

==== United Kingdom

National Biodiversity Network have started a trial with the Environment Agency whereby consultants contracted by the EA under their EcoServices Framework must share their species records directly with the NBN Atlas, and then on to GBIF.

==== United States

• Support GBIF in developing a strategy for marine biodiversity through continued partnership with OBIS.
• Serve as a possible liaison between GBIF and the GEO BON Marine Biodiversity Observation Network.
• Increase coordination across the U.S. related to policy and relevant new partnerships.

==== Uruguay

Contributions to the organization and participation in Experts' Meeting: GBIF in support of the indicators for the Kunming-Montreal Global Biodiversity Framework (Argentina, Colombia, Guatemala, México, Uruguay and Spain)

==== Uzbekistan

As part of the GBIF, Uzbekistan expanded international relations with partner countries, opened access to national biogeographic information, participated in a number of major international seminars and conferences on biodiversity conservation, invasive alien species, disclosure of business information and accessibility of data, information and knowledge, as well as expanded expanded regional mechanisms to support funding and capacity pipelines.

[[wfcc-2]]
==== World Federation for Culture Collections

Again, WFCC congratulates GBIF for the progress made in 2023 and reports presented in Canberra

==== Zimbabwe

Supported national biodiversity commitments by participating in meetings of the National Biodiversity Forum (NBF).

[[plans-priority-3]]
=== Priority Area 3

==== Andorra

- To make the GBIF portal more widely accessible to biodiversity managers in Andorra. To do this we intend to collaborate with neighbouring nodes, , whose knowledge and experience will be invaluable.
- A migration of the GBIF.ad portal to the Google Cloud Platform has been initiated, as well as corrections to the portal so that it can be part of the ALA community. All of this has delayed the objective of making the GBIF.ad portal widely accessible to biodiversity managers in Andorra.

[[acb-3]]
==== ASEAN Centre for Biodiversity

1. Various capacity building towards targeted protected areas in Southeast Asia.
2. Updated the ASEAN Heritage Parks.
3. Updated the species in protected areas in Southeast Asia.

==== Australia

===== 3.2

Support and strengthen GBIF Nodes: ALA will continue to provide active support to the Living Atlases as a sister service to the hosted portals function. 

===== 3.4

Develop capacity and skills: ALA will continue to develop training modules applicable to local conditions. A new training and outreach coordinator will commence early in 2023 and she will be active in developing training materials, running webinars, and identifying future needs.

Ongoing activities: 
Australia will host the GB30 and biennial Global nodes meetings in October this year, in Canberra. This will provide a valuable opportunity to introduce international delegates to Australia and we will be very pleased to offer the opportunity to extend networks and support GBIF nodes and partners. GB30 and the Global nodes meeting will be held in the week after TDWG2023, also planned for Australia. We hope that delegates will take the opportunity to make the most of long flights and participate fully in both meetings. 


==== Belgium

Achieved in 2023: 

* Coordinate the landscape of biodiversity-related initiatives(BIF)
* Pilot on Atlas of Living Flanders
* Possible a first hosted portal(s) for Belgium
* Act as mentor/trainer in GBIF network
* GBIF cloud IPT helpdesk for Europe and Asia

Not achieved or postponed:

* Mobilize training and workshops

==== Benin

Academic capacity building of students in the master program of biodiversity informatics was successfully achieved along with professional capacity building to non academic partners.

[[bhl-3]]
==== Biodiversity Heritage Library

BHL participates in node activities and has hired a Data Manager to represent as Node Manager  in 2021 and Head of Delegation was appointed in 2022.

==== Brazil

We have carried out a large number of virtual training courses and workshops, improved the templates and tutorial videos available on the https://sibbr.gov.br/page/publique-conjunto-dados.html[SiBBr website^], created a https://github.com/sibbr/DarwinCoreBrasil[GitHub^] page to discuss good practices in the use of DarwinCore terms and metadata of collections and projects. We have developed support tools for structuring ecological data. Furthermore, all IPTs were migrated to the cloud and updated to the latest version. Furthermore, we have strengthened the partnership with GBIFPortugal and other Latin American countries after CESP projects as well as Brazil’s participation in meetings held in Canberra.

==== Cameroon

- Enrolment of the University of Ngaoundéré in the GBIF platform.
- Participation in the project to test the new GBIF unified data model.

==== Chile

Over 2023, we promoted in the Chilean community - academics, managers, productive sector, the importance of GBIF and the role of the partners in the success of its implementation and the contribution of open data for science and policy. Multiple workshops and conferences were held to promote the use of standards and open access via the platform.

==== Chinese Academy of Sciences

1. A volunteer team of translators established and started translation work;
2. Joined a training workshop with Uzbekistan team.

==== Chinese Taipei

- Organized regular training workshops on data mobilization and use.
-  Developed a training module for using R in biodiversity data analyses.
- Provided helpdesk services for data providers from non-GBIF participants in Asia. 
- Translated GBIF documents into Traditional Chinese.
- Assisted in GBIF training courses in Asia as trainers and/or mentors.
- Participated in GBIF's engagement and promotion activities in Asia.

==== Colombia

- Within the annual training cycle, the node launch the program: "Corporate Management for Nature, training route towards the mobilization of biodiversity data", during which 337 certificates were generated for 291 participants in the 5 courses offered. Additionally, 4 in-person workshops were held in Colombia, and one international training workshop took place in Australia under the Node Training Program (GBIF), and the participation in 10 events with talks and keynote speeches to promote SiB Colombia. Finally, 21 new licenses for the DataCamp platform were provided to enhance programming skills for data use.
- Support the publication of data from BID program projects involving Colombian participants.

==== Costa Rica

The Node participated in the "Reunión Regional de Nodos LAC GBIF", in wich some countries such as Panama participated as a observers and, hopefully  as Voting Participants in the future. 

[[croatia-3]]

==== Croatia, Republic of

In November 2022, Croatia became a voting member of GBIF network, with Institute for Environment and Nature of the Ministry of Economy and Sustainable Development delegated as Croatian GBIF node. In 2023. first steps towards establishing functional node were made. In order to strengthen the  capacity of Croatian GBIF node, CroMent project was submitted and accepted within GBIF CESP program, in cooperation with the GBIF Belgium and the Habitat Foundation.

==== Denmark

DanBIF continues to provide support, tools and advice to digitisation projects from nature societies, researchers and museums. DanBIF has implemented a new wiki for all aspects of how to share data in GBIF and in the national species portal Arter.dk.

==== East Asia Biodiversity Conservation Network

Encouraged EABCN members to think positively about and contribute to GBIF's data listing. 

==== Estonia

- We started closer collaboration with other national consortia and organisations who create, publish and using the biodiversity data.
- Training of biodiversity data managers in research institutions in Estonia, including GBIF publishing through PlutoF system.  

==== Finland

FinBIF has now been recognised as a "public national authority for nature conservation" under Finland's national Nature Conservation Act. A key indication that the significant effort to communicate the importance of biodiversity data for Finnish Society has been vindicated. In 2023 over 3.7 million new occurrence records were added to the FinBIF database. FinBIF has now published over 40 million records to GBIF. FinBIF mobilised 45 new datasets in 2023. We conducted many training sessions on multiple different topics in 2023. These included, training the use of our web portal, collection management system and data bank system. Training was offered to many stakeholder groups including the government, private and research sectors within Finland.

==== France

- Training and engagement to strengthen and expand national data publication and use is a pillar of our ongoing strategy.
- As NSG chair, french node manager contributed to organize training sessions at the 2023 Global Nodes Meeting addressing needs raised by the nodes committee.
- Collaboration with other nodes and partners to support participation by more countries in GBIF. Finalizing our contribution in 2 BID projects and CESP: 
* Mobilization and strengthening of biodiversity data supporting sustainable development in Côte d'Ivoire, BID national project lead by Ivory Cost
* Progress towards a regional data platform of West and Central African herbaria, BID regional project lead by Togo. 
* CESP mentoring Armenia (new data connected to GBIF).
- Development or enhancement of OpenObs, french data portal on species observation data build on Living Atlasesand promotion of hosted portals (considered for GBIF France website).
- Following of TDWG groups and standards.

==== Georgia

In 2024 the Ministry continues to set up a web-based platform for the Biodiversity Data and Biodiversity Monitoring System, including forest inventory and other data. This information is useful for the General Public to know the information about the state of environment. 

==== Germany

- The collaboration with Czech Republic partners for data mobilisation was continued.
- Capacity building in Africa was continued by collaboration with ITCER e.V. Kenya (https://itcer.org/), GBIF Participant Node Kenya, ICIPE e.V. (http://www.icipe.org/) and several universities in six African countries, i.e. Benin, Cameroon, Egypt, Kenya, Kongo and South Africa. Two on site workshops were held.
- The GBIF Hosted Portal called „Lebendiger Atlas - Natur Deutschland (LAND)“ (https://land.gbif.de/) was established. Guided by NFDI4Biodiversity first datasets were published for GBIF.

==== Ireland

National Biodiversity Data Centre continued to publish all open access data automatically to GBIF. The Data Centre published some datasets through the IPT to meet specific needs of dataset providers (i.e., different data and license types).
Continued engagement with data providers (e.g., government bodies, agencies and museums) to strengthen and expand national data publication and use. Trinity College Dublin was endorsed as a data publisher and published the first Irish fossil dataset from an institution in Ireland. 

==== Madagascar

Data providers will again be asked to publish. Capacity building training (data mobilization, data cleaning, data use and publication) will be organised with the support of a mentor based in Madagascar (Mr Tsiky Rabetrano).
Collaboration with other nodes (in Africa, or France) is also envisaged.

==== Mauritania

- Des activités de sensibilisation et de formation ont été réalisées 
- Revitalize collaboration with local focal points holding biodiversity data.  

==== Mexico

- Continue to collaborate with other nodes on capacity development
- Hosting datasets of publishers without technical capabilities
- Participation in the CESP "Improving GRSciColl records and the visibility of Latin American Natural Science Collections"
- Continue with training and engagement to strengthen and expand national data publication and use.

==== Netherlands

===== Activity 3.1

Report on the economic evaluation of the GBIF network at the annual NLBIF stakeholder event which is scheduled for march 7.

==== Activity 3.2

Within the Dutch landscape there is an urgent need for guidance on publishing sensitive species data.

==== Activity 3.4

- The Dutch node aims to continue the collaboration with Indonesian partners in the BIFA programme and with stakeholders from the Dutch overseas areas in the Caraiben in the BID programme.
- Engage with partners in the Biodiversity Genomics Europe project and the Dutch ARISE project on the training on the mobilisation of DNA derived data to GBIF."

==== New Zealand

- Continued to provided support and guidance to existing and new data providers and interested parties at online meetings and via NZ Hosted Portal (https://www.gbif.org.nz). Attended Global Nodes meeting and worked with other nodes to build capability and seek opportunities including initial discussions for a Living Atlas.
- Report completed for New Zealand regional government providing a process to adopt GBIF as a primary means of preparing, sharing, and accessing publicly available species occurrence data.
- Presentation on GBIF to the New Zealand regional government Data Special Interest Group to promote potential of the GBIF infrastructure to support the data needs of their organisations.

==== Nordic Genetic Resource Center
-We are communicating within the field of GBIF

==== Poland

The Polish National Node organized the Regional GBIF Nodes Meeting in May 2023. The guests represented 12 European country members, 3 observers (Latvia, Lithuania, Ukraine), and 6 associated organizations.

==== South Africa

- Implementation of the CESP Project - SANBI-GBIF and GBIF-Spain partnership to investigate data mining approaches for impactful data use cases and stories.  
- Training curriculum developed and course implemented, entitled: Analytical Techniques in Biodiversity Big Data Using GBIF: Making an Impact 
- Capacitation of approximately 25 participants for the data analysis training and 12 participants for the biodata workshop.  
- Postdoctoral Student appointed to advance species distribution modeling/biodiversity informatics curriculum.

==== Spain

Supporting the Spanish GBIF Community (data publisher as well as users), is the very core of the GBIF Spain action: Thus we maintain a help desk, a team supporting data publication, a yearly training program, a citizen science working area, and pay special attention to communication activities.
  
A highlight in 2023 was the organization of a https://www.gbif.es/talleres/jornada-gbif-es-2023/["GBIF day"^] conceived as a forum for exchanging ideas, pointing areas of interest and future actions, and, of course, identifying and tackling issues.

==== Sweden

- Training and engagement to strengthen and expand national data publication and use. SBDI/GBIF Sweden are planning to have several workshops on how to publish sequence based data as well as sample based data and how to update currently published occurrence datasets to fit this format. 
- Explore possible partnerships and funding opportunities for financing the planned BIECA-project.
-Continue work on stabilizing a dockerized version of the LA infrastructure for SBDI available at https://biodiversitydata.se. Implement the Pipelines module to this system.
- Investigate the interest and possibility of setting up a hosted portal for the Sámpi region together with community partners. Sápmi covers part of Sweden, Norway, Finland and Russia. 


[[tajikistan-3]]
==== Tajikistan, Republic 

We did more but it not enough for Tajikistan. I visited Universities several time to explain for them how is important to share data for future collaboration.

==== Togo

===== Activity 3.1

Activity 3.1 Setting up of the Regional consortium of West and Central Africa Herbaria (between 6 countries) 

==== United Kingdom

DiSSCo UK is developing a national data infrastructure that will integrate the UK’s natural science collections data and make this accessible to all. Part of this infrastructure will be completed in collaboration with GBIF, who are hosting the UK data portal for life science collections. This builds off of an existing GBIF infrastructure that is widely used by the scientific community, with data for millions of UK specimens already available via GBIF. The national portal will aggregate collections data uploaded to GBIF from UK institutions with a GRSciColl (The Global Registry of Scientific Collections) entry

==== United States

- Lead a monthly office hour support session to assist marine data providers with aligning their data to Darwin Core.
- Lead at least one biological data mobilization workshop.
- Contribute to GBIF North America coordination by serving on the GBIF North America Steering Committee.
- Support US data providers / publishers with sharing their data by providing data reviews and access to the GBIF-US IPT.
- Share findings from the economic valuation with the U.S. community.
- More coordinated outreach opportunities across the U.S. community.
==== Uruguay

Development of national workshops to present the initiative, the national portal, and promote the publication of data

==== Uzbekistan

In 2023, Uzbekistan became a leader in the GBIF regional network (Central Asia), thanks to intensified efforts to strengthen partnerships, expand the information base uploaded to GBIF and attract new, especially young scientists from both scientific institutes and regional universities

[[wfcc-3]]
==== World Federation for Culture Collections

Again, WFCC congratulates GBIF for the progress made in 2023 and reports presented in Canberra

==== Zimbabwe

Encourage communities to publish and to use GBIF data.

[[plans-priority-4]]
=== Priority Area 4

==== Andorra

Complete the migration to Google Cloud Platform, set up a new landing page.

A migration of the GBIF.ad portal to Google Cloud Platform has been initiated, as well as corrections to the portal so that it can be part of the ALA community. This part could not be completed due to a lack of available staff.
Collaboration has been initiated with the government of Andorra and the creation of a common biodiversity database is underway."

[[acb-4]]
==== ASEAN Centre for Biodiversity 

1. Purchased new server to host our IPT and other data related repository
2. Established a stable IPT server
3. Provided open access to data contributors using our locally installed IPT
4. Provided help desk support to our data providers 

==== Australia

===== 4.1 

Robustness of GBIF infrastructure: ALA and GBIF have developed and active and collaborative working relationship over the past few years and this will continue in 2023. ALA will continue to collaborate on projects related to the unified data model, and continue to develop the Events system built during 2022. 

===== 4.2

Services for data publishers and users: A significant piece of work planned for 2023 is to update, better integrate and fully revise the taxonomic backbone used by ALA and the code underlying how it is built. New requirements have emerged from the Biosecurity and Restricted Access Species projects that mean that the taxonomic backbone must be much more rigorously built, governed and maintained than it has been in the past. A subject matter expert has been engaged to lead the project and an additional developer is being recruited. We hope to form an active collaboration with the Catalogue of Life and with GBIF to ensure that species found in Australia are represented accurately in the taxonomic schema.

===== 4.3

Enhance features and capabilities: ALA will continue work on the prototype implementation of the Events-based presentation of data. ALA will also actively participate in the further development of the unified data model and how it might be implemented for exemplar data such as genomic data, eDNA and machine observations.

===== 4.4 

Drive data standards development: An ALA staff member is now the Chair of the TDWG Executive during 2023-2024 so this will encourage a standards-focus for the ALA team.

==== Belgium

Achieved in 2023:

* Maintain GBIF Registry and GRSciColl

Not achieved or postponed:

* Support for the unified model (use cases)

==== Benin

GBIF Benin is in progress towards more and more data publication on gbif site.

==== Brazil

The Brazilian node uses the Living Atlas platform. In 2023, new modules were implemented. The entire SiBBr infrastructure uses cloud storage and operates in Kubernetes. The IPTs were migrated to the cloud and updated to the latest version also in Kubernetes. We had access to the GBIF Registry, managing to improve publisher registration and data sharing through GBIF. In addition, we updated the national taxonomic database and it was published in the Living Atlas and IPT.

==== Cameroon

Continued upgrading of Cameroon's Biodiversity Information System.

==== Chile

IPT installation updated and running for publishing partners.

==== Chinese Academy of Sciences

1.Training of GBIF portal tools and projects like rgbif, pyGBIF and hosted portal.

==== Chinese Taipei

- Explored the new data model.
- Engaged with camera-trap and passive acoustic monitoring communities to discuss national standards for machine-generated biodiversity data.
- Developed a data validation tool.
- Developed a data portal for https://tbiadata.tw/en-us/[Taiwan Biodiversity Information Alliance to integrate biodiversity data from 8 government agencies^] 
- Updated https://taicol.tw/en-us/[the web site for the Catalogue of Life in Taiwan^] and https://nametool.taicol.tw/en-us[the management tool for scientific names^]
- Improved the online platform and the data input tool for camera-trap data
- Worked with the Asia support team on the GRSciRoll project

==== Colombia

- A new Colombian hosted portal was developed as result of the participation from the Jardín Botánico de Cartagena in the BID program. 
- The installation of an IPT (Integrated Publishing Toolkit) version 3.0 instance was carried out for testing the new data publishing model (CamTrap DP).

==== Costa Rica

The Node has actively been working on the development and strengthening of the national biodiversity data platform BiodataCR that will greatly contribute to the growth in data publication and use. The Node of Costa Rica, from CONAGEBIO, is strengthening the publication of data coming from citizen science, specially trough the agreement CONAGEBIO-iNaturalist.

==== Croatia, Republic of

Development of national biodiversity database, based on Atlas of Living Australia, started in 2023. 

==== Denmark

DanBIF and DaSSCo has improved the content in GRSciColl regarding Danish natural history collection. DanBIF has implemented an additional IPT installation and a new media server. DanBIF has done initial preparations for implementing a hosted portal for DanBIF. DanBIF has been retiring old static museum datasets and replacing them dynamic datasets being synchronised with museum collection management systems. We are grateful for the speedy and useful help we have received from the GBIF office.

==== Estonia

Support for GBIF data users in Estonia, training, e-mail help.

==== Finland

FinBIF has replaced Google analytics with the more privacy friendly Plausible analytics throughout our web services. In 2023 there were 6 releases of the FinBIF R package. In 2023 the 5th update of the Checklist of Finnish species, FinBIF's taxonomic backbone was released. FinBIF has introduced a new mobile app for Android and iPhone that enhances the gathering of citizen science and other monitoring data. In 2023 the mobile application has been used extensively for the 4th Finnish Breeding Bird Atlas project. We have continued to update and maintain our web portal, API and related services including introducing a new FinBIF Dashboard service to get an overview of various aspects of FinBIF's data and services. In 2023 efforts began to coordinate the organisation of data published to GBIF including improving metadata and moving more datasets from legacy IPTs to automated publishing from FinBIF via the GBIF registry API.

==== France

- Engagement with national collection communities to improve content of the Global Registry of Scientific Collections (GRSciColl)
- Engagement with the diversification of the GBIF data model to address the needs of different national data-holding communities
- Improvements to national informatics infrastructure : maintaining of OpenObs, french observational data portal based on LA portals

==== Georgia

Forest Information and Monitoring System has been developed and serves as the main facility for the data flow in the Forest Sector for all forest management bodies. 

==== Ireland

Maintained and promoted use of of Ireland’s biodiversity mapping portal ‘Biodiversity Maps’.

==== Madagascar

Search for funding for the acquisition of powerful computer equipment
Improve data quality and diversify data for users (researchers, policy makers, students, NGOs etc...)

==== Mauritania

- L'infrastructure logicielle et informatique du GBIF Mauritanie n'est pas opéerationnelle , par manque de serveur, depuis quelques 2015,  et le site est bloqué ce qui n'a pas permis une actualisation de la base de données.
- Look for ways to digitize data and activate the MrBIF site.

==== Mexico

- Continue with training and data quality review in own datasets and data providers datasets.
- Continue with collaboration on translation of GBIF material. Continue with participation in Data model use cases and to review and synchronize the Collections Catalogue with the GRSciColl.

==== Netherlands

===== Activity 4.2

NLBIF will continue to curate the GRSciColl records from Dutch DiSSCo partners and assist in the further mobilisation of specimen derived data to GBIF.

===== Activity 4.3

NLBIF is looking forward to:
- the implementation of the Latimer Core.
- the material catalogue to capture specimen information.
- annotation services.

====== Activity 4.4

NLBIF is looking forward to upload species lists to COL CheckListBank using the GBIF IPT.

==== New Zealand

Through the Secretariat, established a ipt.gbif.org.nz[hosted-IPT GBIF-NZ installation^] as the primary method to support NZ data holders to publish data to GBIF.  

==== Nordic Genetic Resource Center

- We have moved to a new platform 

==== Poland

In 2023 we focused on building a data presentation and management platform for biodversity data mobilised in digization projects, including GBIF Taxonomical Backbone as a reference for taxonomical part of the local database. 

==== South Africa

SANBI-GBIF implements a hosted portal, and has supported the new data model through engaging in efforts to advance molecular data mobilisation.

==== Spain

- We have been working hard re-working our metadata infrastructure, with which we manage a number of core items in our activity: datasets, with all its metadata elements, publication events and quality indicators, the national registry of biodiversity collections and datasets (connected to GRSciColl), training events, news, etc.
- We have been working on our implementation of the https://espacial.gbif.es/?lang=es[ALA's spatial portal^]. Not yet ready for prime time, but mostly working.
- We are actively involved in standard development through our participation in TDWG. Currently, we are leading two standard developments:
* https://www.tdwg.org/community/species/plinian-core/[Plinian core  for species-level information^] 
* https://www.tdwg.org/community/geoschemes/Geoschemes [for area-based species distribution recording^]
- Besides, we are involved in other TDWG activities (participation in other task and Interests groups, organizing symposia, etc.)
- In collaboration with SANBI (GBIF South Africa) and within the framework of a CESP project, we designed, developed and carried out a first edition of a workshop  focused on exploring ways of enabling mining of data and identification of key tools, techniques and approaches that can be used to ask some pertinent research questions related to time, space and taxonomy.

==== Sweden

Engage with national collection communities to improve content of the Global Registry of Scientific Collections (GRSciColl), and clean-up legacy datasets with erroneous publishers.

- Update and remake the front-end and UX/UI for www.gbif.se. 
- Participation and engagement in developing data standards and best practices; participate in TDWG.
- Apply for research infrastructure funding for the period 2025-2028.
- Continue to build the SBDI network in Sweden and promote GBIF within this community. 

[[tajikistan-4]]
==== Tajikistan, Republic 

One thing I didn't do in this year I wanna do it in 2024.

==== Togo

- https://www.african-herbaria.org[Setting up of the regional Herbarium platform^]  
- Connecting West and Central African Herbaria Data: A new Living Atlases regional data platform

==== United Kingdom

- GBIF's GRSciColl will be integrated in the DiSSCo UK portal and act as a one-stop registry for institutional information on natural science collections. Current DiSSCo UK work is focussed on ensuring all UK natural science collections are represented on GRSciColl, enabling their data to be included in the portal. The use of GRSciColl as an aggregator of institutional information will improve the visibility of UK collections, open up opportunities for collaboration and support, and enhance data mobilisation efforts.
- NBN Trust have supported NatureMetrics by formatting the Forestry England eDNA-derived dataset as a Darwin Core Archive, so that NM understand the process and can use it as a template for their other clients.

==== United States

- Lead an OBIS project team to explore early adoption and testing of the new data model to assess how well it works for OBIS community data, noting and sharing back to the data model team any problems encountered, suggestions for improvements, and feasibility of uptake.
- Increase engagement in hosted portal process.

==== Uzbekistan

In Uzbekistan, a permanent GBIF group has been formed on the basis of the Institute of Botany of the Uzbekistan Academy of Sciences, which is the basis of the national infrastructure and information products. In addition, the work activities of this group support and develop the established infrastructure for the promotion of knowledge related to the plant diversity of Uzbekistan.

[[wfcc-4]]
==== World Federation for Culture Collections

Again, WFCC congratulates GBIF for the progress made in 2023 and reports presented in Canberra
