[appendix]
== Participant plans 2024

Towards the end of each year, the GBIF Secretariat asks Participants to outline any work they have aligned to the priority areas identified in the GBIF’s work programme for the upcoming year. This appendix includes the plans Participants provided for 2024.

[[plans-priority-1]]
=== Priority Area 1

==== Andorra

New scientific monitoring programmes have been set up, and we need to continue and also launch new participatory science programmes (collaboration with the Government of Andorra should facilitate this). There has also been a delay in integrating the data into the GBIF (see below).

[[acb-1]]
==== ASEAN Centre for Biodiversity

To continue and expand the technical capacity building and data mobilization in Southeast Asia.

==== Australia

===== Activity 1.1

- ALA continues to experiment with uploading DNA-derived data. There is now a postdoctoral fellow engaged in CSIRO who is looking at the challenges in this area. She was actively engaged in discussions about eDNA data during the TDWG conference in Hobart in 2023 and also participated in the GBIF-run workshop adjacent to the GB30 meeting. 
- The Australian Research Genome Atlas (ARGA) has received funding for another year.

===== Activity 1.2 

The status of the EcoCommons project in Australia has changed and it will move to be run under the auspices of a different university in 2024. How actively ALA will participate in the new iteration of this project is as yet unknown.

==== Belgium

- Advance collaborative activities with soil, freshwater, disease vector and eDNA research communities
* Support biodiversity data mobilization
* Improve visibility of Federal collections
* Atlas of Living Flanders
* Organisation of EBR 3 conference (with NLBIF and LuxBIF), see https://www.biodiversity.be/EBRIII
* Keep an eye on EOSC development
* Networking on IAS

==== Benin

Continue data use to inform decision on biodiversity conservation

==== Biodiversity Heritage Library

Future data deposits are anticipated in 2024, but are wholly dependant on staff capacity to do the data transformation work required.

==== Brazil

Test the GBIF eDNA tool and publish eDNA data. Study in more detail the advantages and disadvantages of implementing DOIs at national level together with other research institutions. Create and follow discussion of research/working groups on FAIR and CARE principles at a national and international level. Automate publishing and updating of occurrence and ecological data in SiBBr and implement test with the new GBIF data model and Humboldt extension. In addition, work together with the group on vectors of human desases by organizing a symposium on vector data and seek for more funding to continue the development of the PREVIR application that allows the collection of virus data in different animals and automatic standardization for publication in the IPT.

==== Cameroon

- Participation in workshops organized by research institutes. These activities are not planned and can take place at any time during the year. Example: Presentation of the GBIF platform and its use as a decision-making tool by policy-makers in Cameroon will be made during a workshop organized by the Institut de Recherche Agricole pour le Développement (IRAD) scheduled for February 07, 2024.
- Support for researchers in the use of GBIF data in the production of scientific articles.

==== Chile

- Promote the mobilization and use of biodiversity data to support research and public policy management. 
- We continue to establish agreements with new partners, transfer or provide assistance to publishers and propose working groups to advance a public policy on biodiversity data.
- By 2024, the node is expected to be consolidated through network-wide governance, which will enable the generation of a roadmap for the next five years.

==== Chinese Academy of Sciences

Country Research Report of GBIF data usage in Asia based on literature data, from different scientific disciplines and thematic areas.

==== Chinese Taipei

- Engage with disease vector, eDNA, alien species and agrobiodiversity research communities and facilitate data publication.
- Identify data gaps in Taiwan and propose a strategy for filling the gaps.
- Provide financial support for data paper publishing.
- Provide helpdesk services for data mobilization.
- Organize workshops and promotion events at scientific conferences.
- Promote applications of biodiversity open data in research on social media.
- Establish data pipelines and help data management for Taiwan's long-term socio-ecological research project.

==== Colombia

- Continue the participation in the national task group on migartory, threatened, and invasive alien species, and publish the national reference checklist on migratory,  invasive, exotic and invasive potential species.
- Strengthen and expand support and guidance on mobilizing DNA-derived, for which we will continue making test in the new tool involving intersted publishers.
- Support and review the new data models developed though GBIF efforts and make internal test to contribute to the reviewing process and capture needs and suggestions from research communities regarding the development of the GBIF data model.
- Promote the Data Use Club within research and student communities as well as the calls for the Ebbe Nielsen Challenge and Graduate Researchers Award.

==== Costa Rica

Establish alliances with representative NGOs that have projects in different areas of the country and in relevant topics (such as alien species, Human-wildlife conflict, biodiversity in human impacted areas, etc) whose biodiversity data is key to filling knowledge gaps in the country. Contact with researchers and projects related to DNA-derived data in the country in order to incorporate this information to GBIF.

[[croatia-1]]
==== Republic of Croatia

Croatia in cooperation with the GBIF Belgium and the Habitat Foundation (within the CroMent project), will conduct workshops that will encourage the mobilization and use of data on biodiversity. Representatives of the scientific community will attend the workshops, which will certainly increase the mobilization of data in the territory of the Republic of Croatia. National biodiversity database, based on Atlas of Living Australia, is expected to be publicly available by September 2024

==== Denmark

The development of the Arter.dk national species portal is continuing in 2024. DanBIF and Arter.dk is working towards supporting collecting and sharing aquatic occurance data including governmental nature monitoring data. Furthermore, we are working towards being able to support sound-based occurrence observations including automated species recognition. DanBIF also keeps the taxonbase in Arter.dk updated  in collaboration with a newly established Danish taxon advisory board. DanBIF plans to implement the new data model specifically to mobilise a large camera trap dataset of small mammals. DanBIF have engaged with new categorise of data providers such as NGO's and nature consultancy companies.

[[eabcn-1]]
==== East Asia Biodiversity Conservation Network

Continue to encourage and support the discovery of undigitized taxonomic information and its inclusion in the GBIF

==== Estonia

We will focus on eDNA data mobilisation and publishing. Updated version of the UNITE SH DOIs will be released and made available for the GBIF taxonomic backbone. New digital tools for the eDNA research will be developed and  implemented in the PlutoF platform which will make sharing and publishing eDNA data easier.

==== Finland

FinBIF and its partners plans to investigate how to mobilise eDNA based biodiversity including soil derived DNA data. A focus for 2024 will be on addressing knowledge gaps within FinBIF's current biodiversity datasets. We plan to address how we make sensitive biodiversity data available to our data users, building on our past work in this area.

==== France

-	Engagement with national research communities relating to data mobilization and use, targeting thematic priorities and French overseas.
-	Contribution on national working groups: WP Traits and WP Sequence.
-	Encourage participation in testing the new data model.
-	Plan to organize a GBIF France day to reinforce visibility and data use in France.
-	Keep track of use through GBIF monitoring.
-	Communicate on outputs of GBIF’s contribution to latest biodiversity modelling approaches (B-Cubed, BioDT…).
-	Consider discussions on data from natural habitat ecosystems.
-	The French node manager is an official member of REISO : French network of international experts organized by the ministry of research to promote open science and French policy regarding open science.

==== Georgia

- Continue research on the ways of entry of invasive alien species in 2024.
- Continue development of the National species restoration plan  for adoption.

==== Germany

The GBIF node delegates, manager and staff will continue to attend relevant scientific conferences to promote GBIF through appropriate communication materials and presentations. They will also participate in GBIF meetings and conferences, e.g. the planned ECA meeting in Zagreb. In 2024, the organisations of the GBIF Germany node network intend to mobilise occurrence and checklist data via data pipelines of the NFDI4Biodiversity consortium. Thus, GBIF is becoming part of the German National Research Data Infrastructure (NFDI).

==== Ireland

As part of the National Biodiversity Action Plan for Ireland (which will be launched in 2024) the National Biodiversity Data Centre is to:
- update to the State of Knowledge and Key Knowledge Gaps in Ireland’s Biodiversity report as the basis for development of a national biodiversity monitoring framework by 2024.
- produce and implement a Biodiversity Citizen Science Strategy to promote citizen engagement with both terrestrial and marine biodiversity and to develop greater awareness of the value of local biodiversity by 2024.
- Ongoing activities to support science and research for different project areas including  All Ireland Pollinator Plan; European Innovation Partnerships projects; Invasive Species, Farmland projects which will produce high quality data.
- Attend relevant scientific conferences to promote GBIF through appropriate communication materials and presentations.

==== Madagascar

- Revitalising the MadBIF network.
- Diversification of data types is among MadBIF's priorities. Data on microorganisms (fungi, bacteria).
- amélirer la base de données sur la biodiversité en Mauritanie et dynamisation des points focaux du GBIF-Mauritanie.

==== Mauritania

- Continue investigation activities into the biodiversity of continental wetlands in Mauritania
- Improve the botanical collection

==== Mexico

- Support implementation of national policies on open science, developing capacity to follow open science practices
- We published the calls, but on this occasion no candidates presented themselves. It has been published on the CONABIO website and we hope to spread it further. In all national and regional forums in which the National Biodiversity Information System (SNIB) is presented, we promote the use of DOIs.

==== Netherlands

===== Activity 1.1

- Priority area Soil: NLBIF puts special attention to soil biodiversity and aims to mobilise more datasets with RIVM
- Priority area DNA barcoding and metagenomics: NLBIF is partner in the MetaPlantCode project that was funded by Biodiversa+ which will mobilise a substantial amount of eDNA data to GBIF over the next three years.
- Priority area Business sector: NLBIF is involved through its host institute - Naturalis Biodiversity Center - in collaborations with KPMG and BNP Paribas where the impacts and dependencies of business activities on biodiversity are assessed. Parts of these analyses depend on biodiversity data mobilzed through GBIF. Through this engagement businesses are also motivated to share their biodiversity data from environmental impact assessments.

===== Activity 1.2
Through the collaboration with KPMG NLBIF aims to inform the private sector on distinguishing the negative impacts on biodiversity of  climate change from the impacts of business activities through predictive modeling.

===== Activity 1.3
The Dutch, Belgium and Luxembourg GBIF nodes organize the https://www.biodiversity.be/EBRIII/[Empowering Biodiversity Research III conference^] on March 25 and 26 at Naturalis Biodiversity Center that promotes sharing and using of GBIF data for research and policy.

==== New Zealand

- We plan to hold a GBIF-NZ workshop with key stakeholders and government agencies to communicate and engage with data holders. This will provide an opportunity to promote the value of GBIF to NZ,  as well as to test and refine the draft strategy, roadmap and workplan for New Zealand. At this we will continue work to identify priority datasets for mobilisation to improve data coverage across the thematic areas of relevance (e.g. invasive species and eDNA). 
- Development of a simple process to increase awareness and applications from NZ to the graduate awards.
- Support newly registered NZ data publishers to mobilise their data sets using the hosted-ipt instance.

==== Nordic Genetic Resource Center

We are working on DOIS to our MCPD data. 

==== Poland

- to continue publishing digitized data through GBIF.
- to include GBIF as a key component of data publishing for all planned large digitization projects in the country.
- to promote GBIF at biodiversity-related scientific conferences.
- to include GBIF usage and data publishing in academic education.

==== South Africa

- Data use and impact of South African data to be taken forward in 2024.  Further efforts to support the mobilization of DNA derived data will be taken forward.  
- GRA will be promoted in 2024 and is supported by a national committee.
- Promote efforts around use and citations of GBIF mediated data, at relevant conferences and stakeholder events as opportunity arises.
- Further efforts to take forward mass digitization efforts using the Conveyor Belt System.
- Take steps to advance work around data paper publication.

==== Spain

- We maintain our core activities (operations) focused on increasing biodiversity data coming from Spanish institutions and projects, and promoting GBIF-mediated data usage. This year we plan to prioritize data coming from the private sector and data related to areas relevant in conservation and ecosystem services as soil and freshwater biodiversity.  
- The 2024 training plan includes two workshops focused on modelling and data cleaning for data modelling. 
- We plan to develop during 2024 some specialized views of GBIF data in https://datos.gbif.es[our data portal^] addressing specific communities (ecologists, managers, schools)."

==== Sweden

===== Activity 1.1: 

Mobilization and use of biodiversity data: GBIF Sweden will continue to focus on mobilizing DNA-derived data and monitoring data. As an integral part of https://biodiversitydata.se/[SBDI^], GBIF Sweden will contribute to the establishment of metagenome sequence catalogs for key Swedish biomes not covered by international efforts. We plan to recruit a data steward (50% FTE) who will conduct more active outreach focused on data mobilization and networking. As part of the introduction the new data steward will make an updated data gap analysis and inventory of possible Swedish data stakeholders. GBIF Sweden will continue to partner with the Swedish National Data Service (SND) to set up a national (research) metadata portal (https://demo.researchdata.se/en[view demo^]). This portal will deliver national data to EOSC.

===== Activity 1.2: 

Biodiversity modelling: Participate in and co-organize the SBDI Days with focus on Data-driven ecology.

===== Activity 1.3: 

Open science principles: Continue to monitor and participate (as reviewer) in the process of producing https://www.kb.se/samverkan-och-utveckling/nationella-riktlinjer-for-oppen-vetenskap/utkast-till-riktlinjer.html[national guidelines for open research and open data^]. We further plan to organize a FAIR data workshop.  

[[tajikistan-1]]
==== Republic of Tajikistan 

In 2024 I'm going to submit new project to CESP. 

==== Togo

===== Activity 1.1. 

GBIF Togo plans to continue mobilizing data on the diseases sector, and using data by modelling in the same area.

===== Activity 1.2

Capture needs and suggestions from Togo public research communities (universities, institutes, NGOs) regarding the development of the GBIF activities (data mobilizing and data use)

==== United Kingdom

Building  on the experience of the live IPNI registration system: https://www.ipni.org/registration/. Kew and Natural History Museum staff will argue and support proposals for registration of plant names at the nomenclatural session of the  International Botanical Congress July 2024 in Madrid.

==== United States

Continue work from 2023, including: 

- Lead an Earth Science Information Partners (ESIP) Cluster to promote the use of standards, e.g. Darwin Core, for biological observation data. 
- Promote the use of the DNA Derived Data extension in US eDNA forums. 
- Contribute to a data dialog session at Ecological Society of America annual meeting in collaboration with key biodiversity data entities. 	
- Develop some more general material to deploy at outreach events, and test e.g, at Entomological Society of America and others 
- Participate in working groups to develop DNA-derived data standards and practices toward a streamlined publication workflow 
- Highlight and illustrate uses of GBIF-mediated data across scientific disciplines and thematic areas through GBIF.US

==== Uruguay

Publishing DNA-derived data. 

==== Uzbekistan

In 2024, Uzbekistan will host a GBIF workshop for the first time with the participation of scientists from Central Asia and other surrounding countries. More than 300,000 georeferenced points will be uploaded to GBIF.

[[wfcc]]
==== World Federation for Culture Collections

Improving biodiversity evidence for scientific research and understanding is long overdue and it is the right action to be taken.

==== Zimbabwe

Mobilise data on bacteria and fungul communities in forest and cropland soils in addition to plants and arthropods.

[[plans-priority-2]]
=== Priority Area 2

==== Andorra

* Continue and advance collaborative activities with public administrations to publish their data on the GBIF portal.
* Collaboration with public administrations, and in particular the Andorran government, has been strengthened and a common database is being created to feed them in order to publish their data on the GBIF portal.


==== ASEAN Centre for Biodiversity

Organized a Bioland Tool workshop for 3 ASEAN Countries with the support from CHM CBD secretariat.

==== Australia

ALA's most relevant work, in addition to advocacy to Australian government regarding international policy commitments, will be to develop standardised data capture tools for data capture in the field. ALA's collaborations with Indigenous Ranger groups is likely to be the catalyst for the development of new tools.

==== Belgium

Achieved in 2023:

* Riparias project ongoing
* IPBES communication products targeted at BE stakeholders 
* Biodiversa  activities

Not achieved or postponed:
* Engaging BE experts in IPBES workplan
* IUCN Belgium Day
* Biodivclim
* Biodivscen

Ongoing activities:

* Finish RipaRIAS project
* Handover Biodiversa+ project to Belspo team
* Establish collaboration with Sciensano on One Health
* Engage BE experts in IPBES, IUCN workplan

==== Benin

Partnership was reinforced through training in the framework of workshop. Researchers, policy and decision makers were invited and attended the workshops.

==== Brazil

New partnerships with Brazilian institutions, technical assistance in data mobilization by government agencies and promoting the use of creative commons licenses as well as dissemination of GBIF Brazil. Recently, in 2023 the Brazilian Institute of Economy and Statistics (IBGE) published the first report on “Quality assessment on Brazilian Biodiversity data” using data available on SiBBr’s (GBIF Brazil). 
More information: https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/38420-ibge-avalia-os-registros-de-dados-sobre-a-biodiversidade-brasileira[BGE assesses data records on Brazilian biodiversity^]  ; https://biblioteca.ibge.gov.br/visualizacao/livros/liv102046.pdf[Avaliação dos dados sobre a biodiversidade brasileira^]

==== Cameroon

Participation à l’atelier de lancement du projet Global Biodiversity Framework Early Action Support (Africa 4)

==== Chile

Incorporate GBIF in the process of implementing the Support implementation of the post-2020 Global Biodiversity Framework in Chile.

==== Chinese Academy of Sciences

1. Node staff attended several CBD & IPBES meetings and communicated with participants about the work of GBIF. 
2. Organized an online webinar to encourage data owners to join the GBIF network.

==== Chinese Taipei

- Engaged with government agencies, companies and consultancies related to environmental impact assessments.
- Collected cases of using biodiversity open data in policy making.
- Organized a data mobilization workshop for environmental impact assessments.
- Engaged with biodiversity-related government agencies through Taiwan Biodiversity Information Alliance.

==== Colombia

From the business sector activities we acquired 13 publishers and reach near to 4 million records total, therefore consolidating the alliance with ANDI through the creation of https://www.gbif.org/es/network/2ee1bff7-0b34-4fa3-9433-feaa7c6ee08b[the Colombian Biodiversity and Development GBIF network^].

==== Costa Rica

We are actively working on the implementation of Creative Commons licenses in our national plataform BiodataCR to facilitate correct citation of the databases and the corresponding credit. Also, we are participating in the CESP project called "Enhancing data publication, access and use capacities in theprivate sector" wich seeks to strengthen collection and publication of data by public and private business sector.

[[croatia-2]]
==== Croatia, Republic of

GBIF accepted the CroMent project that will help in realization of the priority area 2.

==== Denmark

DanBIF is actively involved in increasing the awareness of the importance and strength in the use and provision of data to GBIF towards the industry and financial sector. 

[[eabcn-2]]
==== East Asia Biodiversity Conservation Network

Assess the Red List of Threatened Endemic sprcies in East Asia to implement conservation Biodiversity according to the GBF.

==== Estonia

Estonian GBFI node was involved in the creation of the Environmental commission of the Estonian Academy of Sciences.

==== Finland

In collaboration with the Finnish Environment Institute we have implemented a web-based service for the automatic generation of biodiversity indicators. These indicators can be used to help Finland's relevant bodies in reporting for targets under the Global Biodiversity Framework. FinBIF has frequently engaged directly with ministries and other Finnish government bodies throughout 2023 on nature conservation and environmental decision making. A new GIS data product has been released to aid Finland's 15 Centres for Economic Development, Transport and the Environment in decision making around land-use planning and its impact on threatened species. Biodiversity data search capabilities via our web portal have been enhanced to improve the usability for private sector environmental consultants and forest industry partners. In 2023 there were over 2000 data requests made by this data user type using FinBIF's restricted data services. In 2023 private sector data mobilisation has increased with multiple environmental consultancies sharing occurrence records they have collected via our "Data Bank" service.

==== France

- Continue liaising with CHM focal point and the french BON of GEOBON (lead by PNDB national pole of biodiversity data from the research ministry and SIB Information system for biodiversity from ecology ministry).

- Involvement in EU projects such as Biodiversa  (pilot use-case on DWC and monitoring data) and DiSSco (e.g. : contribution in training work package in DiSSCo prepare).

- Engagement with the business and finance sectors to encourage sharing and use of biodiversity data : Data4Nature (AFD), DEPOBIO (legal repository of observational data from impact studies for private sector), international private companies based in France.

==== Georgia

- Node Manager nominated by Georgia is responsible for setting up the National  Biodiversity Monitoring System.
-  Node manager has participated in the update of the Red List of Georgia, this process has been done for each taxonomic group of species.

==== Germany

Technical Expert Group for the National Biodiversity Indicators held regular meetings to update suite of Biodiversity Indicators. 

==== Ireland

- The National Biodiversity Data Centre ensured that Ireland increased the quantity and quality of its contributions to GBIF through continued collaborative activities with public administrations.
- The National Biodiversity Data Centre provides the information, data and reporting services on behalf of the State Agency with implementation of the EU Regulation on Invasive Alien Species."

==== Madagascar

The synergy between the entities working on biodiversity (CHM Madagascar, IPBES...) and MadBIF will be reinforced

==== Mauritania

Développer le partenariat avec des institutions publiques et privées. Prospect avenues for collaboration with GBIF nodes, in particular the Belgian node. 

==== Mexico

- Increase of 1.2 million occurrence records in 11new datasets. Total of  25,009,927 publisher occurrences.
- Update 975 datasets, mainly due to taxonomy update and geographic validation processes.
- National checklist "Lista de las especies de Ranunculaceae con distribución en México" and "Lista de las especies de Brassicaceae con distribución en México" were published.
- New regional checklist "Lista de especies de abejas nativas del Parque Nacional Barranca del Cupatitzio (Área de montaña), Uruapan, Michoacán, México." was published by new publisher "Instituto de Ecología A.C. Centro Regional del Bajío". 
- Four new publishers: "Universidad Michoacana de San Nicolás de Hidalgo Facultad de Biología"", ""Instituto de Ecología A.C. Centro Regional del Bajío"", ""Universidad Autónoma de Aguascalientes"", and ""ECA Liquefaction S. de R.L. de C.V." ECA is a company of private sector."
- Increase number of occurrence records, checklist and national publishers.

==== Netherlands

===== Activity 2.1

- NLBIF aims to increase the relevance of Dutch biodiversity data for CBD indicators through engagement with relevant stakeholders in the Netherlands.
- NLBIF aims to establish connections with the national focal points for the CBD, CMS, CITES and Ramsar.

===== Activity 2.2

NLBIF aims to link Dutch data publishers that hold marine biodiversity data that is currently shared through the https://www.informatiehuismarien.nl/uk/[Informatiehuis Marien^] to GBIF.

===== Activity 2.3

- NLBIF is working on mobilising species list with protected species according Dutch and EU laws to COL CheckListBank to increase the policy relevance of GBIF mediated biodiversity data.
- NLBIF aims to become active in mobilising data from Environmental Impact Assessment that are commisioned by governmental organisations and financial institutions.
- NLBIF collaborates on a Biodiversa  application which currently is pending decision.

===== Activity 2.4

NLBIF is trying to establish connections with Dutch Investment Companies to mobilise biodiversity data under the implementation of the Equator Principles.

==== New Zealand

- Some progress made by GBIF-NZ node to support implementation of national commitments under the Convention on Biological Diversity (CBD) by meeting with two key central government agencies (Ministry for Primary Industries and Department of Conservation) to identify and seek agreement to mobilise primary invasive species datasets (e.g. weeds and mammal pests). 
- GBIF Node participation in workshops to develop Monitoring and Reporting Framework for Te Mana o te Taiao – Aotearoa New Zealand Biodiversity Strategy to promote the utility of GBIF infrastructure for data mobilisation to support/underpin NZ contribution to post-2020 Global Biodiversity Framework.

[[nigeria-2]]
==== Nigeria, Federal Republic of

To develop partnerships that will benefit policy and society

==== Nordic Genetic Resource Center

We are working within the post-2020 Global Biodiversity Framework 

==== Poland

Established communication with the General Directorate for Environmental Protection, responsible for harmonization of biodiversity monitoring data collected by the Ministry of Climate and Environment and its agencies.

==== South Africa

South Africa has participated on IPBES Knowledge and Data Task Force.

==== Spain

As a follow-up of the 2023 LAC Nodes regional, we identified an emerging opportunity in the new Biological Diversity Framework approved in Montreal, which includes for the first time a ""Monitoring Framework"", which necessarily requires greater participation of science and data-based evidence. In coordination with the LifeWatch ERIC we organized and carried out  an expert meeting for positioning GBIF in the new CBD framework, and to develop a training module for the nodes global community.  This was held in Seville, funded by CSIC (through a EU project), and  having among participants GBIF Node representatives from six countries and GBIF Secretariat
https://www.gbif.es/experts-meeting-gbif-in-support-of-the-indicators-for-the-kunming-montreal-global-biodiversity-framework/
 
Our linkages and collaborations with administrations and policy makers in Spain are strong. A reflection of this is the organization of the 2023 Conference on ""Biodiversity Information and Environmental Administrations"". This a highlight in our https://www.gbif.es/jornada/jornadas-sobre-informacion-de-biodiversidad-y-administraciones-ambientales-2023/[yearly agendas^]

==== Sweden

- Explore possible partnerships and funding opportunities for financing the planned BIECA-project.
- Continue to build the SBDI network in Sweden and promote GBIF within this community.

[[tajikistan-2]]
==== Tajikistan, Republic 

I met with young students which are interesting working with data and database.

==== Togo

===== Activity 2.3
Participating on CABES/IPBES activities (online course on ‘Developping National Science-Policy-Practice Interface Platforms and Networks’ to develop competences and expertise on this area. 

==== United Kingdom

National Biodiversity Network have started a trial with the Environment Agency whereby consultants contracted by the EA under their EcoServices Framework must share their species records directly with the NBN Atlas, and then on to GBIF.

==== United States

• Support GBIF in developing a strategy for marine biodiversity through continued partnership with OBIS.
• Serve as a possible liaison between GBIF and the GEO BON Marine Biodiversity Observation Network.
• Increase coordination across the U.S. related to policy and relevant new partnerships.

==== Uruguay

Contributions to the organization and participation in Experts' Meeting: GBIF in support of the indicators for the Kunming-Montreal Global Biodiversity Framework (Argentina, Colombia, Guatemala, México, Uruguay and Spain)

==== Uzbekistan

As part of the GBIF, Uzbekistan expanded international relations with partner countries, opened access to national biogeographic information, participated in a number of major international seminars and conferences on biodiversity conservation, invasive alien species, disclosure of business information and accessibility of data, information and knowledge, as well as expanded expanded regional mechanisms to support funding and capacity pipelines.

==== World Federation for Culture Collections

Again, WFCC congratulates GBIF for the progress made in 2023 and reports presented in Canberra

==== Zimbabwe

Supported national biodiversity commitments by participating in meetings of the National Biodiversity Forum (NBF).

[[plans-priority-3]]
=== Priority Area 3

==== Andorra

Complete the migration to GCP and complete the rapprochement with the ALA community so as to be able to collaborate better with neighbouring nodes, whose knowledge and experience will be invaluable. The aim is to make the GBIF.ad portal more widely accessible to biodiversity managers in Andorra.

==== ASEAN Centre for Biodiversity

To continue capacity building to targeted audience e.g. protected area managers, museum curators, data curators from universities, inter-governmental organizations

==== Australia

===== 3.4

ALA has now employed a training and outreach coordinator. She has been actively developing and delivering courses with a focus on data providers - including new providers through the data mobilisation grant programs, and users including very successful courses run for industry. These courses were mainly attended by consultants conducting environmental assessments who were particularly interested in efficient ways to query ALA for threatened species distributions. 

ALA and CSIRO successfully hosted the GB30 and Global Nodes meetings in Canberra in October 2023. In addition, an informative and thought-provoking public seminar on the future of collections was held and well received.

==== Belgium

New activities

* Facilitate hosted portals in Belgium

Ongoing activities

* Data publishing/use training/workshop
* Engage new data publishers/users, community building
* Deliver the CESP Croment project https://www.gbif.org/project/CESP2023-006/croment

==== Benin

We will surely progress in the same objective and achieve more depending on the resources available

==== Biodiversity Heritage Library

BHL will continue to participate in node activities.

==== Brazil

Participate more actively in the organization of annual GBIF meetings as well as regional meetings, in addition to submitting a CESP project, contributing to the translation of GBIF documents into Portuguese and disseminating our tools to support data structuring at an international level. In addition, we will continue with training at national level as well as new training in the use of the GitHub tool to discuss good practices in the use of Darwin core terms.

==== Cameroon

Identification and enrolment of new institutions holding biodiversity data in the GBIF platform.
Continued capacity building of national network members on the use of GBIF tools and standards.

==== Chile

Develop alliances with national or international funds, for new or ongoing projects, to promote the work of the Node in the country, and facilitate the mobilization and use of data, and positioning of GBIF.
Promote the specific value that GBIF membership provides through exclusive services and opportunities for participating governments.
Communicating and positioning the GBIF as a data infrastructure and network that supports open data and open science.

==== Chinese Academy of Sciences

1.Skill training for GBIF community function and projects like BIFA，CESP and hosted portal project;
2.Open educational course design for Biodiversity Data and Informatics Training Plan(BDIT)
3.Citizen Science data integration from the way of single user or the entire portal

==== Chinese Taipei

Develop on-line training modules
Organize regular training workshops on data mobilization and use
Provide helpdesk services for data providers from non-GBIF participants in Asia
Translate GBIF documents into Traditional Chinese
Assist in GBIF training courses in Asia as trainers and/or mentors
Participate in GBIF's engagement and promotion activities in Asia

==== Colombia

- Launch the regional training courses for the business sector in LAC under a CESP project (CESP202-010)[https://www.gbif.org/project/CESP2022-010/enhancing-data-publication-access-and-use-capacities-in-the-private-sector ]
- Continue participating with España, Guatemala y Ecuador in the CESP. National portals addressing national challenges to increase awareness and capacity among project partners using national biodiversity data portals.
- Continue training and engagement actions to strengthen and expand national data publication and use."

==== Costa Rica

We will continue carrying out activities to highlight the importance of GBIF and biodiversity data for conservation in the country.

[[croatia-3]]

==== Croatia, Republic of

In order to strengthen the capacity of the Croatian GBIF node, workshops will be held in cooperation with the GBIF Belgium and The Habitat Foundation (CroMent project), after which it will be possible to further promote the work and value of GBIF in the territory of the Republic of Croatia and expand national data publication and use. Further capacity development on the national GBIF node is needed.

==== Denmark

DanBIF continues to provide support, tools and advice to digitisation projects from nature societies, researchers and museums. DanBIF continues to evolve the successful wiki for all aspects of how to share data in GBIF and in the national species portal Arter.dk.

==== East Asia Biodiversity Conservation Network

We are planning to provide support to members who participate in the discovery and sharing of local species occurrence data. 

==== Estonia

- We will make GBIF Estonian node more visible as a hub for data mobilisation. We are co-organising national conference on biodiversity data and will have a specific presentation on GBIF data resources.
- Continuing support for trainings in data use through affiliated institutions. Schools will be also included in trainings.

==== Finland

In 2024 we plant to build on our new status as a 'public national authority for nature conservation' in Finland with the aim of future-proofing the infrastructure and services we have built and will maintain. FinBIF aims to continue to push for more Finnish biodiversity data to be mobilised in particular from the research and tertiary education sector. We will continue to build on and adapt our training suite and will launch and improve a FinBIF knowledge-base.

==== France

- Continue training and workshops
- Maintain IPTs for french and southern partners
- Development or enhancement of OpenObs, French data portal on species observation data build on Living Atlases
- Launch of the new GBIF France hosted portal
- CESP project with Spain on Plinian Core for plant-pollinator interactions (traits data) 
- As chair of the NSG, contribute to the preparation of the next phase of BID program

==== Georgia

In 2024 the Ministry continues to set up a web-based platform for the Biodiversity Data and Biodiversity Monitoring System, including forest inventory and other data. This information is useful for the General Public to know the information about the state of environment. 

==== Germany

- The GBIF node manager and staff plan to continue the promotion of GBIF in Africa by further on site data expert workshops in Kenya.
- The development of the LAND Portal within the NFDi4Biodiversity scope (data from Germany) will be continued. New datasets from nature conservation agencies and citizen science communities will be mobilised.

==== Ireland

-	Continue to engage with data providers (e.g., government bodies, agencies and museums) to strengthen and expand national data publication and use.
-	Target within Ireland’s National Biodiversity Action Plan is establish a system will be in place to facilitate enhanced contributions to EU and international data hubs and networks.
-	Collaboration with other nodes and attend regional Nodes meeting

==== Madagascar

Fundraising for capacity building training  (data mobilization, data cleaning, data use and publication) 
Collaboration with other nodes (in Africa, or France)

==== Mauritania

dynamiser la communication avec les populations et les partenaires
Revitalize collaboration with local focal points holding biodiversity data.  

==== Mexico

"Continue to collaborate with other nodes on capacity development.
Hosting datasets of publishers without technical capabilities.
Training and engagement actions to expand data publication and use."
Communication began with the Institute of Ecology (INECOL) so that at the institution level they are publishers and not just some dataset, which is on track to start in 2024.

==== Netherlands

===== Activity 3.1

- Present the Deloitte report at the annual NLBIF event.
- Promote the use of GBIF data by the private and financial sectors through CSRD and TNFD reporting activities.
- Use the new derived dataset DOIs in forthcoming data papers.
- Expand activities for the Dutch IPBES node hosted by Naturalis Biodiversity Center.

==== Activity 3.2

- Disseminatie the ""Current Best Practices for Generalizing Sensitive Species Occurrence Data"".
- Implement the new data model as soon as it comes available and update the manual for Dutch data publishers.

==== Activity 2.3

- Together with GBIF Norway we aim to organise the GBIF ECA meeting at the Balkans and open up this event for stakeholders from te region to facilitate the expansion of GBIF to new countries within Europe.
- Through two ECA regional support officers located in Bulgaria and Latvia we aim to further expand the GBIF activities towards eastern and south eastern Europe.

===== Activity 2.4

- Organise a GBIF data mobilisation workshop aligned with the scheduled ECA meeting at the Balkans.
- Explore opportunities for a CESP application

==== New Zealand

To build a stronger and stable foundation for the GBIF NZ Node and enhance the data mobilization and use through the network, we are seeking support and resourcing to expand the number of GBIF NZ support roles.

Review the current GBIF guidance and support materials for FAIR and CARE to evaluate improvements required in New Zealand to meet the needs for indigenous data governance, following 2023 consultation.

Promote GBIF and potential of hosted atlases and living portal to key strategic groups engaged with biosecurity and biodiversity reporting and management in NZ.

Explore potential to engage and promote GBIF within the commercial sector in NZ

If resource permits, develop a proposal for the establishment of a GBIF-NZ ambassador programme to support uptake of GBIF within different sectors of the NZ community.

[[nigeria]]
==== Nigeria, Federal Republic of

1)We hope to start with a workshop about data mobilization and data use within the GBIF community and to make Nigerian collections more visible
2)Support biodiversity data mobilization when funds are available

==== Poland

We plan to organize trainings for local scientific, amateur and academic communities, promoting GBIF data sharing and usage. We find necessary to increase awareness of GBIF and biodiversity informatics potential in large audiences, by making use of GBIF ready-to-use training resources, including publishing DNA-derived data.

==== South Africa

Biodata Advanced course content will be made accessible online on the SANBI-GBIF eLearning Platform.  
Further efforts to implement training workshops in DNA derived data, also species distribution modelling and biodiversity informatics. All content to be made available online, on the SANBI-GBIF website.
Video materials of the GBIF Spain CESP project to be made accessible. Other products from this training will also be made accessible as they are finalized.
Work with GBIF Secretariat training programme to take the outcomes of the CESP programme forward, for further evolution of course content at global level so as to be relevant for the Nodes community - supporting reuse and repurposing objectives of the workplan.

==== Spain

"Supporting the Spanish GBIF Community (data publisher as well as users), is the very core of the GBIF Spain action: Thus we maintain a help desk, a team supporting data publication, a yearly training program, a citizen science working area, and pay special attention to communication activities.
 
We plan to launch a new and improved website in 2024. This year we will make a special effort in support of scientific collections and also to support citizen science initiatives so they can produce more useful data. The plan make emphasis on developing software tools (Elysia: Programa de gestión de colecciones de biodiversidad (gbif.es); Darwin Test: Validación y chequeo de datos en formato Darwin Core (gbif.es) and carrying out training events. We keep providing technical support for the iNaturalist Spanish community Una Comunidad para Naturalistas · Natusfera (inaturalist.org)
 
We plan to add new access points in our data portal targeting specific user profiles and get beyond the taxonomic and the institutional views that we currently offer.

==== Sweden

===== Activity 3.1: Communicating the value of GBIF

Continue with training and engagement to strengthen and expand national data publication and use. SBDI/GBIF Sweden are for example hosting a conference on data-driven ecology including several workshops. Continue to promote and communicate GBIF’s value to science, research and innovation.

===== Activity 3.2: Support and strengthen GBIF nodes

Explore possible partnerships and funding opportunities for a new GBIF programme. Collaboration with other nodes and partners to support participation by more countries in GBIF. Monitor and participate in the TDWG work group for implementing CARE principles.

===== Activity 3.3: Expand and strengthen national participation

Continue work on stabilizing a dockerized version of the LA infrastructure for SBDI available at https://biodiversitydata.se. Continue to investigate the interest and promote setting up a hosted portal for the Sámpi region together with community partners. Continue to fix broken data publishing pipelines. We further aim to strengthen the national participation in DiSSCo as well as the collaboration between the national nodes. Investigate the possibilities of hosting a future GB meeting.

===== Activity 3.4: Develop capacity and skills

Revisit the 2023 nodes training material. 

[[tajikistan-3]]
==== Tajikistan, Republic 

If Secretariat will support my project this year I want to organize big workshops to invite Node from EU and from Central Asia. To make Node community in Central Asia 🌏 to show my country and our scientific why we stay member of GBIF and what benefits we will get

==== Togo

- Improve functionality of CHACAO, the African Herbarium Association with systematic, research and funding issues
-	Integrating bioinformatics/biodiversity informatics as course in the new Master implementing at the University of Lome
-	Organizing training workshops bringing together all data stakeholders to strengthen and expand national data publication and use is a pillar of our ongoing strategy.
-	As a coordinator of BID program, continuing collaboration with the project partners to create and animated CHACAO association (African Herbarium Association), working to enlarge the partners consortium to support participation by more countries in GBIF

==== United Kingdom

Work is continuing to  support DiSSCo UK and funding is being sought. The GBIF hosted portal for DiSSCo UK is now live. Engagement within the UK is good but we will continue to build  the community and make more data available to GBIF as digitisation of UK natural science collections accelerates under the DiSSCo UK umbrella

==== United States

Continue work from 2023, including 

- Lead a monthly office hour support session to assist marine data providers with aligning their data to Darwin Core. 
- Lead at least one biological data mobilization workshop. 
- Contribute to GBIF North America coordination by serving on the GBIF North America Steering Committee. 
- Support US data providers / publishers with sharing their data by providing data reviews and access to the GBIF-US IPT. 
- Share findings from the economic valuation with the U.S. community. 
- More coordinated outreach opportunities across the U.S. community. 

Develop communication and collaboration between GBIF-US and regional nodes 

- Regular meetings 
- Develop plan to describe, communicate, and strengthen the awareness of the node and node activities.  
- Develop data analysis examples for sharing on GBIF-US to highlight the utility of US data. 

- Increase stability and sustainability of GBIF-US node by increasing staff and developing short-term positions to create network of knowledge holders. "

==== Uruguay

Development of national workshops to present the initiative, the national portal, and promote the publication of data

==== Uzbekistan

Uzbekistan’s plans for 2024 for priority area 3 fully comply with the indicative tasks of GBIF for 2024

==== World Federation for Culture Collections

Developing the GBIF network to meet future needs and challenges and all subsections in this section are of immense value

==== Zimbabwe

Increase visibility, publication and use of biodiversity data.

[[plans-priority-4]]
=== Priority Area 4

==== Andorra

Complete the migration of the portal to GCP, join the ALA community and set up the joint biodiversity database with the government of Andorra. Then, with the help of neighbouring nodes, see how to transfer the data automatically to the GBIF.ad portal. The aim of all this is to encourage other local authorities to collaborate on the GBIF.ad database.

==== ASEAN Centre for Biodiversity 

1. Continue data management and publishing using the installed IPT
2. Continue updating our system to support data management and enhancement
3. Develop advance API for interoperability of the systems
4. Develop climate change modelling
5. Develop SDM with the Southeast Asia"

==== Australia

===== 4.1 The collaborative work on shared projects with the GBIF team is ongoing. ALA plans to release a version of the Events system in 2024.

===== 4.2

Throughout 2023, significant work to analyse, revise and remodel the ALA taxonomic backbone was undertaken. Three key issues were identified:
•	The merged, composite nature of the taxonomy used in the ALA creates duplications, misplacements and simple errors
•	Taxonomic changes in the current system require the entire ALA to be reindexed making editing difficult and time intensive
•	There is a subset of intractable geographically based taxonomic issues, often related to conservation status, that cannot be handled by the current system including identification of populations and geographic splits.  

An initial tactical response is currently underway, with a longer-term strategic response planned. The ALA spent 2023 reviewing the issues and compiling new lists. The ALA has made great use of ChecklistBank in these reviews. It has enabled testing of dozens of taxonomic backbone scenarios and provided the ability to identify issues in names sources allowing us to work co-operatively with those sources to develop solutions. 

The ALA will be re-indexed with the upgraded taxonomic backbone in January 2024, after which the next stage of work on the strategic response will commence. 

===== 4.3

ALA plans to release a version of the Events system in 2024. Once is this in place, further work will commence building on this work with extensions for genomic data, eDNA and machine observations.

===== 4.4 

Following a successful symposium on restricted access species data at TDWG 2023, a proposal is in development to start up a TDWG Task Group on restricted access data. The intention is to work up an extension to Darwin Core. The charter for this new Task Group, which will be convened by ALA staff, is currently in development.

==== Belgium

Ongoing activities:
* Maintain GBIF Registry and GRSciColl
* Support for the unified model (use case)
* Belgian experts registry, partially based GBIF literature tracking
* Atlas of living Flanders (& beyond)
* Mica dashboard (Muskrat and Coypu monitor) data publication"

==== Benin

We will do our best to progress with data mobilization to support data use to inform decision on biodiversity conservation

==== Biodiversity Heritage Library

"The Smithsonian National Museum of Natural History (NMNH) is the home of three GBIF Associate Participants: BHL, the Biodiversity Heritage Library; EoL, the Encyclopedia of Life; and ITIS, the Integrated Taxonomic Information System.

Associate Participants, NMNH supports the 2024 Work Programme via the GRSciColl roadmap, the continued development of ChecklistBank, and continued integration of collections and biodiversity related information to GBIF. The NMNH commits USD $250,000 to a Special Purpose fund to Priority Area 4, Infrastructure and data products, in support of this GBIF work."

==== Brazil

Organize a Living Atlas community event to exchange knowledge, implement new modules and infrastructure changes for ecological data indexing. API documentation and testing will be carried out to facilitate the use of data and the first version of a tool will be launched that will automatically review the quality of occurrence data in SiBBr.

==== Cameroon

Continued upgrading of Cameroon's Biodiversity Information System with the integration of modules enabling the integration of the new post-2020 Global Biodiversity Framework and the optimal use of GBIF data in national decision-making.

==== Chile

Maintain the IPT upgraded to the latest version.

==== Chinese Academy of Sciences

1.Involve and update GRSciColl catalogue;
2.Journal Cooperation Plan to clean the dataset inside the article and publish via IPT.
3.Herbaria Data Publishing Plan(HDPP):Help data publishing for plant and animal herbara."

==== Chinese Taipei

Apply the new data model to DNA-derived and camera-trap data
Develop national standards for machine-generated biodiversity data
Incorporate the data validation tool into our current data publishing pipeline 
Develop a tool for data cleaning
Develop a data portal for passive acoustic monitoring data
Update the node's data portal
Work with the Asia support team on the GRSciRoll project"

==== Colombia

- Update our IPT instances (8) to enhance functionalities and provide feedback under the development and implementation of the IPT 3.0.
- Continue supporting national proposals for hosted portals, such as the one from Universidad Nacional de Colombia
- Contribute actively to updating GRSciColl and engaging institutions with collections.
- Update our internal quality check routines in anticipation of the future replacement of the GBIF checklist database with ChecklistBank"

==== Costa Rica

The Node will be working with projects collecting eDNA to improve the participation of this researches in GBIF and publication of this type of data. Continue working in the development and maintenance of BiodataCR. We pretendo to increase effort regarding the the registration of collections in GBIF. The node will keep training users through workshops, webinars, meetings and other ways we think is necessary to help researchers in the publication process.

==== Croatia, Republic of

As mentioned in priority 1, within the CroMent project, Croatia GBIF node will start communication with public institutions, scientific and research organizations and present future national biodiversity database, based on Atlas of Living Australia, which will serve as a national platform for publishing biodiversity data and a channel to GBIF. National biodiversity database is expected to be publicly available by September 2024

==== Denmark

DanBIF and DaSSCo will continue to improve the content in GRSciColl regarding Danish natural history collection. DanBIF is planning to upgrade our IPT servers to version 3 and publish its first (camera trap) dataset based on the new GBIF data model. DanBIF  and DaSSCo is working towards implementing hosted portals with GBIF. DanBIF is working towards retiring more old static museum datasets and replacing them dynamic datasets being synchronised with museum collection management systems.

==== Estonia

- We will continue to develop digital infrastructure and tools for the eDNA data. We will also explore possibility to develop specific Data Cubes for the eDNA data.
- Continuing alignment with GBIF overall goals

==== Finland

We plan to integrate the Checklist of Finnish Species into ChecklistBank. In 2024 we plan to update and improve the Finnish data in the Global Registry of Scientific Collections. FinBIF will continue to contribute to the efforts to digitisation of Finnish biological museum collections including launching the new ALICE digitisation infrastructure. We will continue with the development of our web portal in 2024 including adding a new species trait database. FinBIF will investigate how we might adopt evolving biodiversity data standards with a particular focus on how they can aid in the publishing of machine-based observations including automated systems for recording and identifying audio and image data.

==== France

- Update of TAXREF, national checklist 
- Communicate on Global Registry of Scientific Collections (GRSciColl) and engage with national collection communities to improve the content
- Continue to inform on new data model and engage participation on data model use cases 
- Improvements to national informatics infrastructure : maintaining of OpenObs, french observational data portal based on LA portals

==== Georgia

In 2024 the Ministry continues to set up a web-based platform for the Biodiversity Data and Biodiversity Monitoring System, including forest inventory and other data. 

==== Germany

There are plans to improuve the content od GRSciColl (https://scientific-collections.gbif.org/) for all organisations (data publishers) of the GBIF Germany node network.

The national informatics infrastructure might be improuved through new engagements by national funders supporting the adaption of the GBIF data model to the needs of national data-holding communities

==== Ireland
- Continue to promote Ireland’s national mapping portal ‘Biodiversity Maps’ and encourage data providers (e.g., government bodies, agencies and museums) to strengthen and expand national data publication and use.


==== Madagascar

Search for funding for the acquisition of powerful computer equipment
Improve data quality and diversify data for users (researchers, policy makers, students, NGOs etc...)"

==== Mauritania

- Nous comptons sur le GBIF pour activer en 2024 le site Gbif.mr très revheché par nos collaborateurs. Le flux internet est actuellement satisafaisant au niveau de l'ENS.
- Look for ways to digitize data and activate the MrBIF site

==== Mexico

Continue with training and data quality review in own datasets and data providers datasets.
Continue with collaboration on translation of GBIF material. Continue with participation in Data model use cases and to review and synchronize the Collections Catalogue with the GRSciColl."

For taxonomic validation, the CONABIO CAT (114,252 valid or accepted species names) and the COL are used.

The catalog of both Mexican and foreign collections was updated (3,112 collections and 1,332 institutions, of which 814 are Mexican collections and
2,270 foreigners, of which 26 without identifying the country). Currently participating in the CESP “Improving GRSciColl records and the visibility of Latin American Natural Sciences Collections”"

==== Netherlands

===== Activity 4.1

- Advocate the wider use of ChecklistBank
- Include COL and ChecklistBank in EU funded biodiversity projects.
- Promote the use of rgbif and pygbif

===== Activity 4.2

- NLBIF will continue to curate the GRSciColl records from Dutch DiSSCo partners and assist in the further mobilisation of specimen derived data to GBIF.
- Promote the use use of standardized values, including vocabularies.

===== Activity 4.3

- NLBIF is looking for data publishers that hold sampling event datasets to implement the new Humboldt extension.
- Implement the Latimer Core for specimen based datasets hosted by NLBIF's host institute Naturalis Biodiversity Center.

====== Activity 4.4

- Assist in testing of the data publishing models for specimen data with community members in the capacity of DiSSCo-NL National Node representative.

==== New Zealand

Work with NZOR to publish up to date taxonomic checklists for the New Zealand biota.

As resources permit, work with Local Context to promote the use of Biocultural and Traditional Knowledge Labels and Notices, and (as appropriate) work with data providers to include these in their mobilised data.
"

==== Nigeria, Federal Republic of

(1) Lecture about Biodiversity Informatics in the ‘Science and Museum’ graduate
    Course at a University
(2) Attend some National Biodiversity related"

==== Nordic Genetic Resource Center

Further integrate activities

==== Poland

The Polish National Node plans to continue development of the own biodiversity data platform (not connected to existing community tools as Living Atlases or hosted portals). We hope to mobilise funds for creating online tools to display and analyse biodiversity data. As for the GBIF community tools, we plan to get involved in GRSciColl development and enhancement, aiming at cleaning data on the national activities and related organizations. We plan to test new versions of the IPT, test and publish new data model structures, extending our data structures.

==== South Africa

Further efforts around DNA derived data publication.

==== Spain

Besides continuing with our core operations, we plan to carry out a number of concerted actions to enhance the contribution of citizen science to natural history collections (label transcription, specimen annotation). These comprise setting in production an open ICT platform, training workshops and promotion actions.
 
Additionally, we keep our involvement in standard development through our participation in TDWG. We lead two standard developments:
 
Plinian core  for species-level information :
https://www.tdwg.org/community/species/plinian-core/
Geoschemes for area-based species distribution recording
https://www.tdwg.org/community/geoschemes/
Besides we are involved in other TDWG activities (participation in other task and Interests groups, organizing symposia, etc.)
 
We are involved in a CESP project in collaboration with France on capturing and managing species interactions data
https://www.gbif.org/project/CESP2023-011/plinian-core-for-plant-pollinator-interactions

==== Sweden

===== Activity 4.1: Enhance robustness of the core GBIF infrastructure

Continue to build the SBDI network in Sweden and promote GBIF within this community. Work on improving accessibility of gbif.se by e.g. adding Swedish as a language option. Maintain GBIF Registry and curate and update GRSciColl.

===== Activity 4.2: Enhance support services for data publishers and users

Continue work on building an efficient support center joint with the SBDI infrastructure.

===== Activity 4.3: Enhance features and capabilities of the GBIF infrastructure

Promote collaboration and connections between national initiatives and GBIF developments.

===== Activity 4.4: Drive data standards development

As an integral part of SBDI, GBIF Sweden will contribute to the establishment of Darwin Core protocol for exchange of metagenomic data. Monitor and participate in the TDWG work group for implementing CARE principles. Implement the Latimer Core.

==== Tajikistan, Republic 

I will try to register more organizations to GBIF community and help them to publish data.

==== Togo

To maintain and enlarge the regional platform for more african countries

==== United Kingdom

DiSSCo UK support for  GRSciColl will continue.

The first eDNA dataset is now live on the NBN Atlas. It is from a small rewilding project in Aberdeenshire. The records were produced by NatureMetrics, and shared by the landowner. 

==== United States

- Continued from 2023: 
	- Increase engagement in hosted portal process. 
	- Engage in eDNA conversion tool development 

- From GB30 notes:  Smithsonian NMNH intervention: ...NMNH supports the 2024 Work Programme via the GRSciColl roadmap, the continued development of ChecklistBank, and continued integration of collections and biodiversity related information to GBIF. The NMNH commits USD$250,000 to a Special Purpose fund to Priority Area 4, Infrastructure and data products, in support of this GBIF work. Additionally, this support is aligned as a positive contribution to a future US Collection Action Center, which will further catalyze the use of collection data for research and biodiversity policy needs of the United States and all nations...

==== Uzbekistan

Uzbekistan's main plans for 2024 will be based on the Indicative tasks of GBIFfor 2024 and will be aimed at strengthening the infrastructure for promoting knowledge related to biodiversity.

==== World Federation for Culture Collections

Maintain and evolve infrastructure to advance biodiversity-related knowledge is imperative, data sharing, data standards, infrastructure are again of extreme importance. 

==== Zimbabwe

Plans and work program and targets are defined very clearly for 2024 and until 2027. WFCC is ready to support GBIF where needed."
Build collaborations in the region. Strengthen development of IPT. Seek funding to improve infrastructure, data quality, accessibility and associated capacity building.
