[appendix]
== Participant plans 2024

Towards the end of each year, the GBIF Secretariat asks Participants to outline any work they have aligned to the priority areas identified in the GBIF’s work programme for the upcoming year. This appendix includes the plans Participants provided for 2024.

[[plans-priority-1]]
=== Priority Area 1

==== Andorra

New scientific monitoring programmes have been set up, and we need to continue and also launch new participatory science programmes (collaboration with the Government of Andorra should facilitate this). There has also been a delay in integrating the data into the GBIF (see below).

[[acb-1]]
==== ASEAN Centre for Biodiversity

To continue and expand the technical capacity building and data mobilization in Southeast Asia.

==== Australia

===== 1.1

- ALA continues to experiment with uploading DNA-derived data. There is now a postdoctoral fellow engaged in CSIRO who is looking at the challenges in this area. She was actively engaged in discussions about eDNA data during the TDWG conference in Hobart in 2023 and also participated in the GBIF-run workshop adjacent to the GB30 meeting. 
- The Australian Research Genome Atlas (ARGA) has received funding for another year.

===== 1.2 The status of the EcoCommons project in Australia has changed and it will move to be run under the auspices of a different university in 2024. How actively ALA will participate in the new iteration of this project is as yet unknown.  "

==== Belgium

- Advance collaborative activities with soil, freshwater, disease vector and eDNA research communities
* Support biodiversity data mobilization
* Improve visibility of Federal collections
* Atlas of Living Flanders
* Organisation of EBR 3 conference (with NLBIF and LuxBIF), see https://www.biodiversity.be/EBRIII
* Keep an eye on EOSC development
* Networking on IAS
"

==== Benin

Continue data use to inform decision on biodiversity conservation

[[bhl-1]]
==== Biodiversity Heritage Library

Future data deposits are anticipated in 2024, but are wholly dependant on staff capacity to do the data transformation work required.

==== Brazil

Test the GBIF eDNA tool and publish eDNA data. Study in more detail the advantages and disadvantages of implementing DOIs at national level together with other research institutions. Create and follow discussion of research/working groups on FAIR and CARE principles at a national and international level. Automate publishing and updating of occurrence and ecological data in SiBBr and implement test with the new GBIF data model and Humboldt extension. In addition, work together with the group on vectors of human desases by organizing a symposium on vector data and seek for more funding to continue the development of the PREVIR application that allows the collection of virus data in different animals and automatic standardization for publication in the IPT.

==== Cameroon

- Participation in workshops organized by research institutes. These activities are not planned and can take place at any time during the year. Example: Presentation of the GBIF platform and its use as a decision-making tool by policy-makers in Cameroon will be made during a workshop organized by the Institut de Recherche Agricole pour le Développement (IRAD) scheduled for February 07, 2024.
- Support for researchers in the use of GBIF data in the production of scientific articles.

==== Chile

- Promote the mobilization and use of biodiversity data to support research and public policy management. 
- We continue to establish agreements with new partners, transfer or provide assistance to publishers and propose working groups to advance a public policy on biodiversity data.
- By 2024, the node is expected to be consolidated through network-wide governance, which will enable the generation of a roadmap for the next five years.

Chinese Academy of Sciences
Country Research Report of GBIF data usage in Asia based on literature data, from different scientific disciplines and thematic areas.

==== Chinese Taipei

- Engage with disease vector, eDNA, alien species and agrobiodiversity research communities and facilitate data publication
Identify data gaps in Taiwan and propose a strategy for filling the gaps
Provide financial support for data paper publishing
Provide helpdesk services for data mobilization
- Organize workshops and promotion events at scientific conferences
- Promote applications of biodiversity open data in research on social media
- Establish data pipelines and help data management for Taiwan's long-term socio-ecological research project

==== Colombia

- Continue the participation in the national task group on migartory, threatened, and invasive alien species, and publish the national reference checklist on migratory,  invasive, exotic and invasive potential species.
- Strengthen and expand support and guidance on mobilizing DNA-derived, for which we will continue making test in the new tool involving intersted publishers.
- Support and review the new data models developed though GBIF efforts and make internal test to contribute to the reviewing process and capture needs and suggestions from research communities regarding the development of the GBIF data model.
- Promote the Data Use Club within research and student communities as well as the calls for the Ebbe Nielsen Challenge and Graduate Researchers Award.

==== Costa Rica

Establish alliances with representative NGOs that have projects in different areas of the country and in relevant topics (such as alien species, Human-wildlife conflict, biodiversity in human impacted areas, etc) whose biodiversity data is key to filling knowledge gaps in the country. Contact with researchers and projects related to DNA-derived data in the country in order to incorporate this information to GBIF.

[[croatia-1]]
==== Republic of Croatia

Croatia in cooperation with the GBIF Belgium and the Habitat Foundation (within the CroMent project), will conduct workshops that will encourage the mobilization and use of data on biodiversity. Representatives of the scientific community will attend the workshops, which will certainly increase the mobilization of data in the territory of the Republic of Croatia. National biodiversity database, based on Atlas of Living Australia, is expected to be publicly available by September 2024

==== Denmark

The development of the Arter.dk national species portal is continuing in 2024. DanBIF and Arter.dk is working towards supporting collecting and sharing aquatic occurance data including governmental nature monitoring data. Furthermore, we are working towards being able to support sound-based occurrence observations including automated species recognition. DanBIF also keeps the taxonbase in Arter.dk updated  in collaboration with a newly established Danish taxon advisory board. DanBIF plans to implement the new data model specifically to mobilise a large camera trap dataset of small mammals. DanBIF have engaged with new categorise of data providers such as NGO's and nature consultancy companies.

[[eabcn-1]]
==== East Asia Biodiversity Conservation Network

Continue to encourage and support the discovery of undigitized taxonomic information and its inclusion in the GBIF

==== Estonia

We will focus on eDNA data mobilisation and publishing. Updated version of the UNITE SH DOIs will be released and made available for the GBIF taxonomic backbone. New digital tools for the eDNA research will be developed and  implemented in the PlutoF platform which will make sharing and publishing eDNA data easier.

==== Finland

FinBIF and its partners plans to investigate how to mobilise eDNA based biodiversity including soil derived DNA data. A focus for 2024 will be on addressing knowledge gaps within FinBIF's current biodiversity datasets. We plan to address how we make sensitive biodiversity data available to our data users, building on our past work in this area.

==== France

-	Engagement with national research communities relating to data mobilization and use, targeting thematic priorities and French overseas
-	Contribution on national working groups: WP Traits and WP Sequence 
-	Encourage participation in testing the new data model
-	Plan to organize a GBIF France day to reinforce visibility and data use in France
-	Keep track of use through GBIF monitoring
-	Communicate on outputs of GBIF’s contribution to latest biodiversity modelling approaches (B-Cubed, BioDT…)
-	Consider discussions on data from natural habitat ecosystems
-	The French node manager is an official member of REISO : French network of international experts organized by the ministry of research to promote open science and French policy regarding open science.

==== Georgia

- Continue research on the ways of entry of invasive alien species in 2024.
- Continue development of the National species restoration plan  for adoption.

==== Germany

The GBIF node delegates, manager and staff will continue to attend relevant scientific conferences to promote GBIF through appropriate communication materials and presentations. They will also participate in GBIF meetings and conferences, e.g. the planned ECA meeting in Zagreb. In 2024, the organisations of the GBIF Germany node network intend to mobilise occurrence and checklist data via data pipelines of the NFDI4Biodiversity consortium. Thus, GBIF is becoming part of the German National Research Data Infrastructure (NFDI).

==== Ireland

- As part of the National Biodiversity Action Plan for Ireland (which will be launched in 2024) the National Biodiversity Data Centre is to:
  - update to the State of Knowledge and Key Knowledge Gaps in Ireland’s Biodiversity report as the basis for development of a national biodiversity monitoring framework by 2024
  - produce and implement a Biodiversity Citizen Science Strategy to promote citizen engagement with both terrestrial and marine biodiversity and to develop greater awareness of the value of local biodiversity by 2024
-	Ongoing activities to support science and research for different project areas including  All Ireland Pollinator Plan; European Innovation Partnerships projects; Invasive Species, Farmland projects which will produce high quality data
-	Attend relevant scientific conferences to promote GBIF through appropriate communication materials and presentations

==== Madagascar

- Revitalising the MadBIF network
- Diversification of data types is among MadBIF's priorities. Data on microorganisms (fungi, bacteria)
- amélirer la base de données sur la biodiversité en Mauritanie et dynamisation des points focaux du GBIF-Mauritanie

==== Mauritania

- Continue investigation activities into the biodiversity of continental wetlands in Mauritania
- Improve the botanical collection"

==== Mexico

- Support implementation of national policies on open science, developing capacity to follow open science practices
- We published the calls, but on this occasion no candidates presented themselves. It has been published on the CONABIO website and we hope to spread it further. In all national and regional forums in which the National Biodiversity Information System (SNIB) is presented, we promote the use of DOIs.

==== Netherlands

===== Activity 1.1

- Priority area Soil: NLBIF puts special attention to soil biodiversity and aims to mobilise more datasets with RIVM
- Priority area DNA barcoding and metagenomics: NLBIF is partner in the MetaPlantCode project that was funded by Biodiversa+ which will mobilise a substantial amount of eDNA data to GBIF over the next three years.
- Priority area Business sector: NLBIF is involved through its host institute - Naturalis Biodiversity Center - in collaborations with KPMG and BNP Paribas where the impacts and dependencies of business activities on biodiversity are assessed. Parts of these analyses depend on biodiversity data mobilzed through GBIF. Through this engagement businesses are also motivated to share their biodiversity data from environmental impact assessments.

===== Activity 1.2
Through the collaboration with KPMG NLBIF aims to inform the private sector on distinguishing the negative impacts on biodiversity of  climate change from the impacts of business activities through predictive modeling.

===== Activity 1.3
The Dutch, Belgium and Luxembourg GBIF nodes organize the https://www.biodiversity.be/EBRIII/[Empowering Biodiversity Research III conference^] on March 25 and 26 at Naturalis Biodiversity Center that promotes sharing and using of GBIF data for research and policy.

==== New Zealand

- We plan to hold a GBIF-NZ workshop with key stakeholders and government agencies to communicate and engage with data holders. This will provide an opportunity to promote the value of GBIF to NZ,  as well as to test and refine the draft strategy, roadmap and workplan for New Zealand. At this we will continue work to identify priority datasets for mobilisation to improve data coverage across the thematic areas of relevance (e.g. invasive species and eDNA). 
- Development of a simple process to increase awareness and applications from NZ to the graduate awards.
- Support newly registered NZ data publishers to mobilise their data sets using the hosted-ipt instance

==== Nordic Genetic Resource Center

We are working on DOIS to our MCPD data 

==== Poland

- to continue publishing digitized data through GBIF
- to include GBIF as a key component of data publishing for all planned large digitization projects in the country
- to promote GBIF at biodiversity-related scientific conferences
- to include GBIF usage and data publishing in academic education

==== South Africa

- Data use and impact of South African data to be taken forward in 2024.  Further efforts to support the mobilization of DNA derived data will be taken forward.  
- GRA will be promoted in 2024 and is supported by a national committee.
- Promote efforts around use and citations of GBIF mediated data, at relevant conferences and stakeholder events as opportunity arises.
- Further efforts to take forward mass digitization efforts using the Conveyor Belt System.
- Take steps to advance work around data paper publication.

==== Spain

- We maintain our core activities (operations) focused on increasing biodiversity data coming from Spanish institutions and projects, and promoting GBIF-mediated data usage. This year we plan to prioritize data coming from the private sector and data related to areas relevant in conservation and ecosystem services as soil and freshwater biodiversity.  
- The 2024 training plan includes two workshops focused on modelling and data cleaning for data modelling. 
- We plan to develop during 2024 some specialized views of GBIF data in https://datos.gbif.es[our data portal^] addressing specific communities (ecologists, managers, schools)."

==== Sweden

===== Activity 1.1: Mobilization and use of biodiversity data

GBIF Sweden will continue to focus on mobilizing DNA-derived data and monitoring data. As an integral part of https://biodiversitydata.se/[SBDI^], GBIF Sweden will contribute to the establishment of metagenome sequence catalogs for key Swedish biomes not covered by international efforts. We plan to recruit a data steward (50% FTE) who will conduct more active outreach focused on data mobilization and networking. As part of the introduction the new data steward will make an updated data gap analysis and inventory of possible Swedish data stakeholders. GBIF Sweden will continue to partner with the Swedish National Data Service (SND) to set up a national (research) metadata portal (https://demo.researchdata.se/en[view demo^]). This portal will deliver national data to EOSC.

===== Activity 1.2: Biodiversity modelling

Participate in and co-organize the SBDI Days with focus on Data-driven ecology.

===== Activity 1.3: Open science principles

Continue to monitor and participate (as reviewer) in the process of producing https://www.kb.se/samverkan-och-utveckling/nationella-riktlinjer-for-oppen-vetenskap/utkast-till-riktlinjer.html[national guidelines for open research and open data^]. We further plan to organize a FAIR data workshop.  

[[tajikistan-1]]
==== Republic of Tajikistan 

In 2024 I'm going to submit new project to CESP. 

==== Togo

===== Activity 1.1. 

GBIF Togo plans to continue mobilizing data on the diseases sector, and using data by modelling in the same area.

===== Activity 1.2

Capture needs and suggestions from Togo public research communities (universities, institutes, NGOs) regarding the development of the GBIF activities (data mobilizing and data use)

==== United Kingdom

Building  on the experience of the live IPNI registration system: https://www.ipni.org/registration/. Kew and Natural History Museum staff will argue and support proposals for registration of plant names at the nomenclatural session of the  International Botanical Congress July 2024 in Madrid.

==== United States

Continue work from 2023, including: 

- Lead an Earth Science Information Partners (ESIP) Cluster to promote the use of standards, e.g. Darwin Core, for biological observation data. 
- Promote the use of the DNA Derived Data extension in US eDNA forums. 
- Contribute to a data dialog session at Ecological Society of America annual meeting in collaboration with key biodiversity data entities. 	
- Develop some more general material to deploy at outreach events, and test e.g, at Entomological Society of America and others 
- Participate in working groups to develop DNA-derived data standards and practices toward a streamlined publication workflow 
- Highlight and illustrate uses of GBIF-mediated data across scientific disciplines and thematic areas through GBIF.US

==== Uruguay

Publishing DNA-derived data 

==== Uzbekistan

In 2024, Uzbekistan will host a GBIF workshop for the first time with the participation of scientists from Central Asia and other surrounding countries. More than 300,000 georeferenced points will be uploaded to GBIF

[[wfcc]]
==== World Federation for Culture Collections

Improving biodiversity evidence for scientific research and understanding is long overdue and it is the right action to be taken

==== Zimbabwe

Mobilise data on bacteria and fungul communities in forest and cropland soils in addition to plants and arthropods

[[plans-priority-2]]
=== Priority Area 2



[[plans-priority-3]]
=== Priority Area 3



[[plans-priority-4]]
=== Priority Area 4
